# Some Models
> To avoid copy-pasta

In [ ]:
# default_exp resnet_models

In [ ]:
# hide
import blackhc.project.script
from nbdev.showdoc import *

In [ ]:
# exports
from dataclasses import dataclass
from typing import Optional

import torch
from torch import nn
import torch.optim
from torch.nn import Module
from torch.utils.data import Dataset, DataLoader

from batchbald_redux.active_learning import RandomFixedLengthSampler
from batchbald_redux.black_box_model_training import train_with_cosine_annealing, train_with_schedule
from batchbald_redux.consistent_mc_dropout import (
    BayesianModule,
    ConsistentMCDropout,
)
from batchbald_redux.model_optimizer_factory import ModelOptimizer, ModelOptimizerFactory

In [ ]:
# exports

from torch import Tensor
from torch.hub import load_state_dict_from_url
from torch.nn import functional as F

from batchbald_redux.trained_model import ModelTrainer, TrainedModel, TrainedBayesianModel

model_urls = {
    "resnet18": "https://download.pytorch.org/models/resnet18-5c106cde.pth",
    "resnet34": "https://download.pytorch.org/models/resnet34-333f7ec4.pth",
    "resnet50": "https://download.pytorch.org/models/resnet50-19c8e357.pth",
    "resnet101": "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth",
    "resnet152": "https://download.pytorch.org/models/resnet152-b121ed2d.pth",
    "resnext50_32x4d": "https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth",
    "resnext101_32x8d": "https://download.pytorch.org/models/resnext101_32x8d-8ba56ff5.pth",
}


def conv3x3(in_planes, out_planes, stride=1, groups=1, dilation=1):
    """3x3 convolution with padding"""
    return nn.Conv2d(
        in_planes,
        out_planes,
        kernel_size=3,
        stride=stride,
        padding=dilation,
        groups=groups,
        bias=False,
        dilation=dilation,
    )


def conv1x1(in_planes, out_planes, stride=1):
    """1x1 convolution"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride, bias=False)


class BasicBlock(nn.Module):
    expansion = 1

    def __init__(
            self, inplanes, planes, stride=1, downsample=None, groups=1, base_width=64, dilation=1, norm_layer=None
    ):
        super(BasicBlock, self).__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        if groups != 1 or base_width != 64:
            raise ValueError("BasicBlock only supports groups=1 and base_width=64")
        if dilation > 1:
            raise NotImplementedError("Dilation > 1 not supported in BasicBlock")
        # Both self.conv1 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out


class Bottleneck(nn.Module):
    expansion = 4

    def __init__(
            self, inplanes, planes, stride=1, downsample=None, groups=1, base_width=64, dilation=1, norm_layer=None
    ):
        super(Bottleneck, self).__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        width = int(planes * (base_width / 64.0)) * groups
        # Both self.conv2 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv1x1(inplanes, width)
        self.bn1 = norm_layer(width)
        self.conv2 = conv3x3(width, width, stride, groups, dilation)
        self.bn2 = norm_layer(width)
        self.conv3 = conv1x1(width, planes * self.expansion)
        self.bn3 = norm_layer(planes * self.expansion)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out


class BayesianResNet(BayesianModule):
    def __init__(
            self,
            block,
            layers,
            num_classes=1000,
            zero_init_residual=False,
            groups=1,
            width_per_group=64,
            replace_stride_with_dilation=None,
            norm_layer=None,
    ):
        super().__init__()

        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        self._norm_layer = norm_layer

        self.inplanes = 64
        self.dilation = 1
        if replace_stride_with_dilation is None:
            # each element in the tuple indicates if we should replace
            # the 2x2 stride with a dilated convolution instead
            replace_stride_with_dilation = [False, False, False]
        if len(replace_stride_with_dilation) != 3:
            raise ValueError(
                "replace_stride_with_dilation should be None "
                "or a 3-element tuple, got {}".format(replace_stride_with_dilation)
            )
        self.groups = groups
        self.base_width = width_per_group

        # This gets reset when cifar_mod=True below
        self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3, bias=False)
        self.bn1 = norm_layer(self.inplanes)
        self.relu = nn.ReLU(inplace=True)

        # This gets reset when cifar_mod=True
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2, dilate=replace_stride_with_dilation[0])
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2, dilate=replace_stride_with_dilation[1])
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2, dilate=replace_stride_with_dilation[2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))

        self.fc = nn.Linear(512 * block.expansion, num_classes)
        self.fc = nn.Sequential(
            ConsistentMCDropout(),
            nn.Linear(512 * block.expansion, 256 * block.expansion),
            nn.ReLU(),
            ConsistentMCDropout(),
            nn.Linear(256 * block.expansion, 256 * block.expansion),
            nn.Linear(256, num_classes),
        )
        # self.fc = nn.Sequential(
        #     nn.ReLU(),
        #     nn.Linear(512 * block.expansion, 256 * block.expansion),
        #     ConsistentMCDropout(),
        #     nn.Linear(256 * block.expansion, 128 * block.expansion),
        #     ConsistentMCDropout(),
        #     nn.Linear(128 * block.expansion, 128 * block.expansion),
        #     nn.ReLU(),
        #     nn.Linear(128 * block.expansion, num_classes),
        # )

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

        # Zero-initialize the last BN in each residual branch,
        # so that the residual branch starts with zeros, and each residual block behaves like an identity.
        # This improves the model by 0.2~0.3% according to https://arxiv.org/abs/1706.02677
        if zero_init_residual:
            for m in self.modules():
                if isinstance(m, Bottleneck):
                    nn.init.constant_(m.bn3.weight, 0)
                elif isinstance(m, BasicBlock):
                    nn.init.constant_(m.bn2.weight, 0)

    def _make_layer(self, block, planes, blocks, stride=1, dilate=False):
        norm_layer = self._norm_layer
        downsample = None
        previous_dilation = self.dilation
        if dilate:
            self.dilation *= stride
            stride = 1
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                conv1x1(self.inplanes, planes * block.expansion, stride), norm_layer(planes * block.expansion)
            )

        layers = []
        layers.append(
            block(
                self.inplanes, planes, stride, downsample, self.groups, self.base_width, previous_dilation, norm_layer
            )
        )
        self.inplanes = planes * block.expansion
        for _ in range(1, blocks):
            layers.append(
                block(
                    self.inplanes,
                    planes,
                    groups=self.groups,
                    base_width=self.base_width,
                    dilation=self.dilation,
                    norm_layer=norm_layer,
                )
            )

        return nn.Sequential(*layers)

    def deterministic_forward_impl(self, x: Tensor):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.reshape(x.size(0), -1)

        return x

    def mc_forward_impl(self, x: Tensor):
        x = self.fc(x)
        x = F.log_softmax(x, dim=-1)
        return x


def _bayesian_resnet(arch, block, layers, cifar_mod, pretrained, progress, **kwargs):
    model = BayesianResNet(block, layers, **kwargs)
    if cifar_mod:
        model.conv1 = torch.nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
        model.maxpool = torch.nn.Identity()

    if pretrained:
        assert not cifar_mod
        state_dict = load_state_dict_from_url(model_urls[arch], progress=progress)
        model.load_state_dict(state_dict, strict=False)

    return model


def bayesian_resnet18(*, cifar_mod=False, pretrained=False, progress=True, **kwargs):
    """Constructs a ResNet-18 model.

    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
        progress (bool): If True, displays a progress bar of the download to stderr
    """
    return _bayesian_resnet("resnet18", BasicBlock, [2, 2, 2, 2], cifar_mod, pretrained, progress, **kwargs)


def bayesian_resnet34(*, cifar_mod=False, pretrained=False, progress=True, **kwargs):
    """Constructs a ResNet-34 model.

    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
        progress (bool): If True, displays a progress bar of the download to stderr
    """
    return _bayesian_resnet("resnet34", BasicBlock, [3, 4, 6, 3], cifar_mod, pretrained, progress, **kwargs)

In [ ]:
# exports


class Cifar10BayesianResnetFactory(ModelOptimizerFactory):
    def create_model_optimizer(self) -> ModelOptimizer:
        model = bayesian_resnet18(cifar_mod=True, num_classes=10)
        optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=5e-4)
        return ModelOptimizer(model=model, optimizer=optimizer)


_dataloader_kwargs = dict(num_workers=4, pin_memory=True)


@dataclass
class Cifar10ModelTrainer(ModelTrainer):
    device: str

    num_training_samples: int = 1
    num_validation_samples: int = 20
    max_training_epochs: int = 300
    patience_schedule: [int] = (10, 10, 5)
    factor_schedule: [int] = (0.1,)

    min_samples_per_epoch: int = 5056
    num_training_batch_size: int = 128
    num_evaluation_batch_size: int = 512

    @staticmethod
    def create_model_optimizer() -> ModelOptimizer:
        model = bayesian_resnet18(cifar_mod=True, num_classes=10)
        optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=5e-4)
        return ModelOptimizer(model=model, optimizer=optimizer)

    def get_train_dataloader(self, dataset: Dataset):
        train_loader = DataLoader(
            dataset,
            batch_size=self.num_training_batch_size,
            sampler=RandomFixedLengthSampler(dataset, self.min_samples_per_epoch),
            drop_last=True,
            **_dataloader_kwargs
        )
        return train_loader

    def get_evaluation_dataloader(self, dataset: Dataset):
        evaluation_loader = DataLoader(
            dataset, batch_size=self.num_evaluation_batch_size, drop_last=False, shuffle=False,
            **_dataloader_kwargs
        )
        return evaluation_loader

    def get_trained(self, *, train_loader: DataLoader, train_augmentations: Optional[Module],
                    validation_loader: DataLoader, log, loss=None, validation_loss=None) -> TrainedModel:
        model_optimizer = self.create_model_optimizer()

        if loss is None:
            loss = torch.nn.NLLLoss()
        if validation_loss is None:
            validation_loss = torch.nn.NLLLoss()

        if False:
            print("With Patience")
            train_with_schedule(
                model=model_optimizer.model,
                optimizer=model_optimizer.optimizer,
                training_samples=self.num_training_samples,
                validation_samples=self.num_validation_samples,
                train_loader=train_loader,
                train_augmentations=train_augmentations,
                validation_loader=validation_loader,
                patience_schedule=self.patience_schedule,
                factor_schedule=self.factor_schedule,
                max_epochs=self.max_training_epochs,
                loss=loss,
                validation_loss=validation_loss,
                device=self.device,
                training_log=log,
            )
        else:
            print("Cosine Annealing")
            train_with_cosine_annealing(
                model=model_optimizer.model,
                optimizer=model_optimizer.optimizer,
                training_samples=self.num_training_samples,
                validation_samples=self.num_validation_samples,
                train_loader=train_loader,
                train_augmentations=train_augmentations,
                validation_loader=validation_loader,
                max_epochs=self.max_training_epochs,
                loss=loss,
                validation_loss=validation_loss,
                device=self.device,
                training_log=log
            )

        return TrainedBayesianModel(model_optimizer.model)

## CIFAR-10 40% baseline

In [ ]:
# experiment

from batchbald_redux.datasets import get_dataset
from batchbald_redux.black_box_model_training import evaluate

In [ ]:
# experiment 
split_dataset = get_dataset("CIFAR-10", root="data", normalize_like_cifar10=False, validation_set_size=5000)

Files already downloaded and verified
Files already downloaded and verified


In [ ]:
# experiment

from torch.utils import data

model_trainer = Cifar10ModelTrainer(device="cuda")

train_loader = model_trainer.get_train_dataloader(split_dataset.train * 0.4)
print(len(train_loader.dataset))
validation_loader = model_trainer.get_evaluation_dataloader(split_dataset.validation)
test_loader = model_trainer.get_evaluation_dataloader(split_dataset.test)

log = {}
trained_model = model_trainer.get_trained(train_loader=train_loader, train_augmentations=split_dataset.train_augmentations, validation_loader=validation_loader, log=log)

18000
Cosine Annealing


  0%|          | 1/300 [00:00<?, ?it/s]

[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 1 metrics: {'accuracy': 0.2856, 'crossentropy': 1.8545497650146485}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 2 metrics: {'accuracy': 0.3292, 'crossentropy': 1.9277066995620729}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 3 metrics: {'accuracy': 0.4584, 'crossentropy': 1.534279344177246}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 4 metrics: {'accuracy': 0.498, 'crossentropy': 1.4638728162765502}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 5 metrics: {'accuracy': 0.5098, 'crossentropy': 1.437373586654663}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 6 metrics: {'accuracy': 0.5594, 'crossentropy': 1.3292468334197998}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 7 metrics: {'accuracy': 0.6114, 'crossentropy': 1.163236389541626}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 8 metrics: {'accuracy': 0.5862, 'crossentropy': 1.226002060508728}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 9 metrics: {'accuracy': 0.6426, 'crossentropy': 1.0702646913528442}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 10 metrics: {'accuracy': 0.661, 'crossentropy': 1.0213278537750243}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 11 metrics: {'accuracy': 0.6952, 'crossentropy': 0.9394193833351135}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 12 metrics: {'accuracy': 0.6614, 'crossentropy': 0.9984549903869628}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 13 metrics: {'accuracy': 0.6828, 'crossentropy': 1.0071536222457886}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 14 metrics: {'accuracy': 0.708, 'crossentropy': 0.9346793626785278}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 15 metrics: {'accuracy': 0.7324, 'crossentropy': 0.8567409112930298}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 16 metrics: {'accuracy': 0.7352, 'crossentropy': 0.8462186522483826}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 17 metrics: {'accuracy': 0.7158, 'crossentropy': 0.9333689485549926}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 18 metrics: {'accuracy': 0.7558, 'crossentropy': 0.8051220417976379}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 19 metrics: {'accuracy': 0.6974, 'crossentropy': 1.034203429222107}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 20 metrics: {'accuracy': 0.7742, 'crossentropy': 0.7360812670707703}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 21 metrics: {'accuracy': 0.7702, 'crossentropy': 0.7432255446434021}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 22 metrics: {'accuracy': 0.782, 'crossentropy': 0.7339959760665894}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 23 metrics: {'accuracy': 0.7646, 'crossentropy': 0.8096233380317688}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 24 metrics: {'accuracy': 0.7802, 'crossentropy': 0.7205158989906311}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 25 metrics: {'accuracy': 0.7536, 'crossentropy': 0.7887222961425782}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 26 metrics: {'accuracy': 0.7716, 'crossentropy': 0.8186643391609192}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 27 metrics: {'accuracy': 0.7692, 'crossentropy': 0.7962150002479553}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 28 metrics: {'accuracy': 0.8002, 'crossentropy': 0.6736455117225647}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 29 metrics: {'accuracy': 0.7864, 'crossentropy': 0.7181077597618103}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 30 metrics: {'accuracy': 0.7872, 'crossentropy': 0.7404170677185059}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 31 metrics: {'accuracy': 0.779, 'crossentropy': 0.7604064460754395}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 32 metrics: {'accuracy': 0.7766, 'crossentropy': 0.8294541075706482}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 33 metrics: {'accuracy': 0.7964, 'crossentropy': 0.7467875930786133}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 34 metrics: {'accuracy': 0.7868, 'crossentropy': 0.8013256266593933}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 35 metrics: {'accuracy': 0.7656, 'crossentropy': 0.8753616209030152}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 36 metrics: {'accuracy': 0.8204, 'crossentropy': 0.6367582839965821}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 37 metrics: {'accuracy': 0.8242, 'crossentropy': 0.6399408193588256}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 38 metrics: {'accuracy': 0.8062, 'crossentropy': 0.7217883975982666}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 39 metrics: {'accuracy': 0.8152, 'crossentropy': 0.6884591849327087}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 40 metrics: {'accuracy': 0.8016, 'crossentropy': 0.7723951833724976}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 41 metrics: {'accuracy': 0.8196, 'crossentropy': 0.6628482033729554}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 42 metrics: {'accuracy': 0.8118, 'crossentropy': 0.7181119831085205}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 43 metrics: {'accuracy': 0.8124, 'crossentropy': 0.6956645809173584}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 44 metrics: {'accuracy': 0.7956, 'crossentropy': 0.8467483345031739}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 45 metrics: {'accuracy': 0.8092, 'crossentropy': 0.7528219615936279}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 46 metrics: {'accuracy': 0.7892, 'crossentropy': 0.9269635530471801}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 47 metrics: {'accuracy': 0.8328, 'crossentropy': 0.6333340282440185}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 48 metrics: {'accuracy': 0.8022, 'crossentropy': 0.7965955832481384}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 49 metrics: {'accuracy': 0.824, 'crossentropy': 0.6557772603988647}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 50 metrics: {'accuracy': 0.8074, 'crossentropy': 0.8091998703956604}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 51 metrics: {'accuracy': 0.7956, 'crossentropy': 0.9136038031578064}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 52 metrics: {'accuracy': 0.8342, 'crossentropy': 0.6638007917404175}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 53 metrics: {'accuracy': 0.8362, 'crossentropy': 0.6500532857894897}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 54 metrics: {'accuracy': 0.8294, 'crossentropy': 0.6875188645362854}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 55 metrics: {'accuracy': 0.8334, 'crossentropy': 0.6365359700202942}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 56 metrics: {'accuracy': 0.8106, 'crossentropy': 0.8157225450515747}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 57 metrics: {'accuracy': 0.7856, 'crossentropy': 1.0377094486236573}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 58 metrics: {'accuracy': 0.8354, 'crossentropy': 0.6808976434707642}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 59 metrics: {'accuracy': 0.8184, 'crossentropy': 0.7892855514526367}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 60 metrics: {'accuracy': 0.798, 'crossentropy': 0.9396205501556396}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 61 metrics: {'accuracy': 0.8248, 'crossentropy': 0.7595659711837769}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 62 metrics: {'accuracy': 0.8034, 'crossentropy': 0.9257151521682739}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 63 metrics: {'accuracy': 0.8424, 'crossentropy': 0.6549510976791382}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 64 metrics: {'accuracy': 0.825, 'crossentropy': 0.7364507520675659}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 65 metrics: {'accuracy': 0.8368, 'crossentropy': 0.7309814467430115}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 66 metrics: {'accuracy': 0.8336, 'crossentropy': 0.7399176309585571}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 67 metrics: {'accuracy': 0.842, 'crossentropy': 0.6872009261131287}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 68 metrics: {'accuracy': 0.8178, 'crossentropy': 0.8373127025604248}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 69 metrics: {'accuracy': 0.8438, 'crossentropy': 0.685840180683136}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 70 metrics: {'accuracy': 0.8378, 'crossentropy': 0.7026629771232605}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 71 metrics: {'accuracy': 0.8336, 'crossentropy': 0.7679980454444886}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 72 metrics: {'accuracy': 0.8456, 'crossentropy': 0.6975786490440369}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 73 metrics: {'accuracy': 0.8238, 'crossentropy': 0.8190247141838074}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 74 metrics: {'accuracy': 0.8438, 'crossentropy': 0.73705371799469}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 75 metrics: {'accuracy': 0.8386, 'crossentropy': 0.7477448069572449}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 76 metrics: {'accuracy': 0.8482, 'crossentropy': 0.6885799756050109}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 77 metrics: {'accuracy': 0.8376, 'crossentropy': 0.7597014122009277}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 78 metrics: {'accuracy': 0.841, 'crossentropy': 0.8079666268348694}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 79 metrics: {'accuracy': 0.8506, 'crossentropy': 0.721381614112854}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 80 metrics: {'accuracy': 0.8434, 'crossentropy': 0.778343196105957}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 81 metrics: {'accuracy': 0.8526, 'crossentropy': 0.6730792145729065}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 82 metrics: {'accuracy': 0.8212, 'crossentropy': 0.9540710098266602}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 83 metrics: {'accuracy': 0.8494, 'crossentropy': 0.6839977670669556}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 84 metrics: {'accuracy': 0.8536, 'crossentropy': 0.7026290508270263}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 85 metrics: {'accuracy': 0.8498, 'crossentropy': 0.7334547729492188}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 86 metrics: {'accuracy': 0.846, 'crossentropy': 0.7746248898506165}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 87 metrics: {'accuracy': 0.8528, 'crossentropy': 0.6996674884796142}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 88 metrics: {'accuracy': 0.838, 'crossentropy': 0.7748713617324829}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 89 metrics: {'accuracy': 0.8442, 'crossentropy': 0.7649139569282531}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 90 metrics: {'accuracy': 0.851, 'crossentropy': 0.703072527217865}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 91 metrics: {'accuracy': 0.8528, 'crossentropy': 0.6958219986915588}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 92 metrics: {'accuracy': 0.8368, 'crossentropy': 0.7910226912498474}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 93 metrics: {'accuracy': 0.8574, 'crossentropy': 0.6537726356506348}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 94 metrics: {'accuracy': 0.8614, 'crossentropy': 0.6826119378089904}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 95 metrics: {'accuracy': 0.8426, 'crossentropy': 0.8041058448791504}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 96 metrics: {'accuracy': 0.8328, 'crossentropy': 0.8932533625602722}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 97 metrics: {'accuracy': 0.8472, 'crossentropy': 0.7472060799598694}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 98 metrics: {'accuracy': 0.8412, 'crossentropy': 0.8056079147338867}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 99 metrics: {'accuracy': 0.8494, 'crossentropy': 0.7593761708259582}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 100 metrics: {'accuracy': 0.8508, 'crossentropy': 0.7163452644348145}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 101 metrics: {'accuracy': 0.8458, 'crossentropy': 0.753485200881958}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 102 metrics: {'accuracy': 0.8616, 'crossentropy': 0.6732524274826049}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 103 metrics: {'accuracy': 0.8404, 'crossentropy': 0.8011472591400146}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 104 metrics: {'accuracy': 0.845, 'crossentropy': 0.75767584400177}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 105 metrics: {'accuracy': 0.86, 'crossentropy': 0.7234556740760804}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 106 metrics: {'accuracy': 0.8606, 'crossentropy': 0.6999372383117676}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 107 metrics: {'accuracy': 0.8564, 'crossentropy': 0.7358453497886658}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 108 metrics: {'accuracy': 0.8468, 'crossentropy': 0.8046362591743469}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 109 metrics: {'accuracy': 0.8374, 'crossentropy': 0.8557856467247009}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 110 metrics: {'accuracy': 0.8496, 'crossentropy': 0.7620479378700257}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 111 metrics: {'accuracy': 0.8522, 'crossentropy': 0.7193976620674133}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 112 metrics: {'accuracy': 0.8528, 'crossentropy': 0.7287584713935852}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 113 metrics: {'accuracy': 0.8532, 'crossentropy': 0.7560758545875549}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 114 metrics: {'accuracy': 0.8438, 'crossentropy': 0.8252616525650024}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 115 metrics: {'accuracy': 0.8514, 'crossentropy': 0.7799418643951416}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 116 metrics: {'accuracy': 0.8488, 'crossentropy': 0.8075506601333619}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 117 metrics: {'accuracy': 0.8552, 'crossentropy': 0.7097553594589233}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 118 metrics: {'accuracy': 0.866, 'crossentropy': 0.6738803176879883}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 119 metrics: {'accuracy': 0.8618, 'crossentropy': 0.7208435382843018}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 120 metrics: {'accuracy': 0.8572, 'crossentropy': 0.7373522766113281}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 121 metrics: {'accuracy': 0.8338, 'crossentropy': 0.9548956916809082}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 122 metrics: {'accuracy': 0.8602, 'crossentropy': 0.6994466906547546}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 123 metrics: {'accuracy': 0.8672, 'crossentropy': 0.6992287550926208}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 124 metrics: {'accuracy': 0.8666, 'crossentropy': 0.7011544188499451}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 125 metrics: {'accuracy': 0.861, 'crossentropy': 0.7161647013664245}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 126 metrics: {'accuracy': 0.8672, 'crossentropy': 0.6650666800498962}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 127 metrics: {'accuracy': 0.8696, 'crossentropy': 0.691644019985199}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 128 metrics: {'accuracy': 0.8654, 'crossentropy': 0.6885326607704163}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 129 metrics: {'accuracy': 0.8578, 'crossentropy': 0.7805585440635681}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 130 metrics: {'accuracy': 0.871, 'crossentropy': 0.6927882253646851}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 131 metrics: {'accuracy': 0.863, 'crossentropy': 0.7523870921134949}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 132 metrics: {'accuracy': 0.8562, 'crossentropy': 0.7506723625183106}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 133 metrics: {'accuracy': 0.8664, 'crossentropy': 0.7025162903785706}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 134 metrics: {'accuracy': 0.8642, 'crossentropy': 0.7176886338233948}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 135 metrics: {'accuracy': 0.8646, 'crossentropy': 0.7192893412590027}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 136 metrics: {'accuracy': 0.855, 'crossentropy': 0.7549131596565246}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 137 metrics: {'accuracy': 0.8708, 'crossentropy': 0.6984952207565308}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 138 metrics: {'accuracy': 0.8684, 'crossentropy': 0.6908443077087403}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 139 metrics: {'accuracy': 0.8684, 'crossentropy': 0.6770447429656983}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 140 metrics: {'accuracy': 0.862, 'crossentropy': 0.685473792552948}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 141 metrics: {'accuracy': 0.8656, 'crossentropy': 0.7229589156150817}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 142 metrics: {'accuracy': 0.8686, 'crossentropy': 0.6789560466766358}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 143 metrics: {'accuracy': 0.8734, 'crossentropy': 0.6885281230926513}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 144 metrics: {'accuracy': 0.8638, 'crossentropy': 0.7147123766899108}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 145 metrics: {'accuracy': 0.8726, 'crossentropy': 0.6722450366020203}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 146 metrics: {'accuracy': 0.8668, 'crossentropy': 0.7223228028297425}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 147 metrics: {'accuracy': 0.8696, 'crossentropy': 0.7305106444358825}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 148 metrics: {'accuracy': 0.8676, 'crossentropy': 0.6805039556503296}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 149 metrics: {'accuracy': 0.8674, 'crossentropy': 0.7053425640106201}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 150 metrics: {'accuracy': 0.863, 'crossentropy': 0.7328518979072571}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 151 metrics: {'accuracy': 0.8712, 'crossentropy': 0.6749421430587769}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 152 metrics: {'accuracy': 0.8748, 'crossentropy': 0.6622314817428588}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 153 metrics: {'accuracy': 0.8744, 'crossentropy': 0.6548304243087768}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 154 metrics: {'accuracy': 0.8758, 'crossentropy': 0.6484699404716492}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 155 metrics: {'accuracy': 0.868, 'crossentropy': 0.6999514840126038}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 156 metrics: {'accuracy': 0.8708, 'crossentropy': 0.6997609419822692}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 157 metrics: {'accuracy': 0.8734, 'crossentropy': 0.7046216305732727}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 158 metrics: {'accuracy': 0.8762, 'crossentropy': 0.6821415965080261}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 159 metrics: {'accuracy': 0.8702, 'crossentropy': 0.6919474114418029}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 160 metrics: {'accuracy': 0.8724, 'crossentropy': 0.7077758668899536}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 161 metrics: {'accuracy': 0.8762, 'crossentropy': 0.691142723941803}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 162 metrics: {'accuracy': 0.872, 'crossentropy': 0.6785869790077209}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 163 metrics: {'accuracy': 0.8802, 'crossentropy': 0.64453285446167}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 164 metrics: {'accuracy': 0.8752, 'crossentropy': 0.6522824264526367}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 165 metrics: {'accuracy': 0.8782, 'crossentropy': 0.6569128186225891}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 166 metrics: {'accuracy': 0.8772, 'crossentropy': 0.6522456070899963}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 167 metrics: {'accuracy': 0.8768, 'crossentropy': 0.6587914772033692}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 168 metrics: {'accuracy': 0.8808, 'crossentropy': 0.650617962360382}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 169 metrics: {'accuracy': 0.8778, 'crossentropy': 0.6405186521530152}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 170 metrics: {'accuracy': 0.8804, 'crossentropy': 0.6306645065307617}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 171 metrics: {'accuracy': 0.8824, 'crossentropy': 0.6277330803871155}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 172 metrics: {'accuracy': 0.8842, 'crossentropy': 0.634911201953888}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 173 metrics: {'accuracy': 0.8848, 'crossentropy': 0.6472932760238648}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 174 metrics: {'accuracy': 0.8812, 'crossentropy': 0.6192628698348999}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 175 metrics: {'accuracy': 0.8792, 'crossentropy': 0.6423950766563415}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 176 metrics: {'accuracy': 0.8792, 'crossentropy': 0.6570449501037597}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 177 metrics: {'accuracy': 0.8824, 'crossentropy': 0.6550199915885925}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 178 metrics: {'accuracy': 0.8834, 'crossentropy': 0.6283490198135376}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 179 metrics: {'accuracy': 0.8842, 'crossentropy': 0.6220402395248413}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 180 metrics: {'accuracy': 0.8874, 'crossentropy': 0.6278664695739746}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 181 metrics: {'accuracy': 0.882, 'crossentropy': 0.6533350936889648}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 182 metrics: {'accuracy': 0.8858, 'crossentropy': 0.6367190044403076}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 183 metrics: {'accuracy': 0.8842, 'crossentropy': 0.6244511122703552}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 184 metrics: {'accuracy': 0.8792, 'crossentropy': 0.6344222054481506}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 185 metrics: {'accuracy': 0.88, 'crossentropy': 0.6288470969200134}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 186 metrics: {'accuracy': 0.8834, 'crossentropy': 0.6233252975463868}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 187 metrics: {'accuracy': 0.8828, 'crossentropy': 0.6126835848808289}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 188 metrics: {'accuracy': 0.8822, 'crossentropy': 0.62097612657547}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 189 metrics: {'accuracy': 0.8828, 'crossentropy': 0.5974698554992676}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 190 metrics: {'accuracy': 0.883, 'crossentropy': 0.6193984685897828}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 191 metrics: {'accuracy': 0.8848, 'crossentropy': 0.6072008012771607}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 192 metrics: {'accuracy': 0.8818, 'crossentropy': 0.6194289293289185}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 193 metrics: {'accuracy': 0.8838, 'crossentropy': 0.6068023470878601}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 194 metrics: {'accuracy': 0.8854, 'crossentropy': 0.5973319814682007}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 195 metrics: {'accuracy': 0.8844, 'crossentropy': 0.6199771155357361}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 196 metrics: {'accuracy': 0.882, 'crossentropy': 0.6171613084793091}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 197 metrics: {'accuracy': 0.8854, 'crossentropy': 0.5921084924697876}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 198 metrics: {'accuracy': 0.8818, 'crossentropy': 0.6241772885322571}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 199 metrics: {'accuracy': 0.8852, 'crossentropy': 0.597427645111084}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 200 metrics: {'accuracy': 0.8834, 'crossentropy': 0.5921060774803162}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 201 metrics: {'accuracy': 0.8844, 'crossentropy': 0.5941774314880371}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 202 metrics: {'accuracy': 0.8862, 'crossentropy': 0.5887086565017701}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 203 metrics: {'accuracy': 0.8862, 'crossentropy': 0.5922266948699951}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 204 metrics: {'accuracy': 0.8864, 'crossentropy': 0.5924130989074707}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 205 metrics: {'accuracy': 0.8866, 'crossentropy': 0.5928044528007508}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 206 metrics: {'accuracy': 0.8866, 'crossentropy': 0.5902848583221435}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 207 metrics: {'accuracy': 0.886, 'crossentropy': 0.5854803153038025}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 208 metrics: {'accuracy': 0.8852, 'crossentropy': 0.5830728775978088}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 209 metrics: {'accuracy': 0.8854, 'crossentropy': 0.5821076240539551}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 210 metrics: {'accuracy': 0.8858, 'crossentropy': 0.5769341907501221}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 211 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5652683254241944}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 212 metrics: {'accuracy': 0.886, 'crossentropy': 0.5674199729919434}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 213 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5732382596969604}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 214 metrics: {'accuracy': 0.8878, 'crossentropy': 0.5762968244552612}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 215 metrics: {'accuracy': 0.8864, 'crossentropy': 0.5726380308151245}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 216 metrics: {'accuracy': 0.8876, 'crossentropy': 0.569606763458252}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 217 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5632205394744874}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 218 metrics: {'accuracy': 0.8868, 'crossentropy': 0.5655683919906617}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 219 metrics: {'accuracy': 0.8878, 'crossentropy': 0.5721477480888366}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 220 metrics: {'accuracy': 0.889, 'crossentropy': 0.5749097256660461}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 221 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5699309700965881}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 222 metrics: {'accuracy': 0.8904, 'crossentropy': 0.5623799489974975}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 223 metrics: {'accuracy': 0.8878, 'crossentropy': 0.5649431234359741}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 224 metrics: {'accuracy': 0.8884, 'crossentropy': 0.5615118761062622}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 225 metrics: {'accuracy': 0.888, 'crossentropy': 0.5721969318389892}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 226 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5655677375793458}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 227 metrics: {'accuracy': 0.8866, 'crossentropy': 0.5643915587425232}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 228 metrics: {'accuracy': 0.8874, 'crossentropy': 0.5717823468208313}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 229 metrics: {'accuracy': 0.8904, 'crossentropy': 0.563829190826416}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 230 metrics: {'accuracy': 0.8894, 'crossentropy': 0.561688598537445}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 231 metrics: {'accuracy': 0.8882, 'crossentropy': 0.5561195303916932}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 232 metrics: {'accuracy': 0.8886, 'crossentropy': 0.5569055274963379}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 233 metrics: {'accuracy': 0.8874, 'crossentropy': 0.5591052185058594}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 234 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5619488019943237}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 235 metrics: {'accuracy': 0.8906, 'crossentropy': 0.55289466714859}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 236 metrics: {'accuracy': 0.8884, 'crossentropy': 0.5621278694152833}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 237 metrics: {'accuracy': 0.888, 'crossentropy': 0.560072559928894}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 238 metrics: {'accuracy': 0.8886, 'crossentropy': 0.5565862071990967}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 239 metrics: {'accuracy': 0.8872, 'crossentropy': 0.5680286551475525}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 240 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5613680129051208}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 241 metrics: {'accuracy': 0.888, 'crossentropy': 0.5582245405197144}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 242 metrics: {'accuracy': 0.888, 'crossentropy': 0.5672383170127868}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 243 metrics: {'accuracy': 0.8858, 'crossentropy': 0.5582973077774048}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 244 metrics: {'accuracy': 0.8884, 'crossentropy': 0.5530762175559998}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 245 metrics: {'accuracy': 0.8868, 'crossentropy': 0.559892483139038}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 246 metrics: {'accuracy': 0.8878, 'crossentropy': 0.5517046320915222}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 247 metrics: {'accuracy': 0.886, 'crossentropy': 0.5505643743515015}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 248 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5559379597663879}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 249 metrics: {'accuracy': 0.8898, 'crossentropy': 0.5522927379608155}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 250 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5519060923576355}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 251 metrics: {'accuracy': 0.8888, 'crossentropy': 0.5511935290336609}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 252 metrics: {'accuracy': 0.8864, 'crossentropy': 0.5495532639503479}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 253 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5490799542427063}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 254 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5532227585792542}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 255 metrics: {'accuracy': 0.888, 'crossentropy': 0.5596931102752686}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 256 metrics: {'accuracy': 0.8872, 'crossentropy': 0.5523460603713989}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 257 metrics: {'accuracy': 0.8902, 'crossentropy': 0.5434131070137024}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 258 metrics: {'accuracy': 0.8894, 'crossentropy': 0.5493420634269714}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 259 metrics: {'accuracy': 0.8902, 'crossentropy': 0.5456006191253662}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 260 metrics: {'accuracy': 0.8894, 'crossentropy': 0.5460159462928772}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 261 metrics: {'accuracy': 0.8902, 'crossentropy': 0.552637745475769}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 262 metrics: {'accuracy': 0.8894, 'crossentropy': 0.5497317007064819}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 263 metrics: {'accuracy': 0.8884, 'crossentropy': 0.5570216917991638}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 264 metrics: {'accuracy': 0.8868, 'crossentropy': 0.5517818427085877}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 265 metrics: {'accuracy': 0.8886, 'crossentropy': 0.5460380856513977}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 266 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5437191630363465}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 267 metrics: {'accuracy': 0.8912, 'crossentropy': 0.5481618978500367}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 268 metrics: {'accuracy': 0.8902, 'crossentropy': 0.5451211562156677}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 269 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5521842562675476}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 270 metrics: {'accuracy': 0.8874, 'crossentropy': 0.5430374388694763}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 271 metrics: {'accuracy': 0.888, 'crossentropy': 0.5483050139427185}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 272 metrics: {'accuracy': 0.8868, 'crossentropy': 0.5483657761573791}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 273 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5414332080841064}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 274 metrics: {'accuracy': 0.8894, 'crossentropy': 0.5544344073295593}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 275 metrics: {'accuracy': 0.8904, 'crossentropy': 0.5478388912200928}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 276 metrics: {'accuracy': 0.8908, 'crossentropy': 0.5519512662887573}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 277 metrics: {'accuracy': 0.8914, 'crossentropy': 0.5468340723991394}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 278 metrics: {'accuracy': 0.889, 'crossentropy': 0.5476910656929016}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 279 metrics: {'accuracy': 0.8908, 'crossentropy': 0.5396752041816711}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 280 metrics: {'accuracy': 0.8896, 'crossentropy': 0.543235572719574}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 281 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5425547796249389}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 282 metrics: {'accuracy': 0.8906, 'crossentropy': 0.5452956100463867}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 283 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5486729020118714}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 284 metrics: {'accuracy': 0.8888, 'crossentropy': 0.5486828422546387}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 285 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5463020894050599}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 286 metrics: {'accuracy': 0.8884, 'crossentropy': 0.5451721060752869}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 287 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5483986428260803}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 288 metrics: {'accuracy': 0.8876, 'crossentropy': 0.5477032614707946}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 289 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5468354002952576}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 290 metrics: {'accuracy': 0.8888, 'crossentropy': 0.5541053038597107}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 291 metrics: {'accuracy': 0.8888, 'crossentropy': 0.5460178703308105}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 292 metrics: {'accuracy': 0.8894, 'crossentropy': 0.5467668138504028}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 293 metrics: {'accuracy': 0.89, 'crossentropy': 0.5452041365623475}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 294 metrics: {'accuracy': 0.8886, 'crossentropy': 0.5521361680984497}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 295 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5496299787521363}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 296 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5530377503395081}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 297 metrics: {'accuracy': 0.8874, 'crossentropy': 0.5526186201095581}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 298 metrics: {'accuracy': 0.89, 'crossentropy': 0.5443681015968322}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 299 metrics: {'accuracy': 0.8896, 'crossentropy': 0.5474069827079773}


[1/140]   1%|           [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 300 metrics: {'accuracy': 0.8892, 'crossentropy': 0.5428712361335755}


In [ ]:
# experiment

evaluate(model=trained_model, num_samples=20, loader=test_loader, device="cuda")

get_predictions_labels:   0%|          | 0/200000 [00:00<?, ?it/s]

{'accuracy': 0.8923, 'crossentropy': tensor(0.4584)}

In [ ]:
# experiment

from torch.utils import data

model_trainer = Cifar10ModelTrainer(device="cuda")

train_loader = model_trainer.get_train_dataloader(split_dataset.train * 0.1)
validation_loader = model_trainer.get_evaluation_dataloader(split_dataset.validation)
test_loader = model_trainer.get_evaluation_dataloader(split_dataset.test)

log = {}
trained_model = model_trainer.get_trained(train_loader=train_loader, train_augmentations=split_dataset.train_augmentations, validation_loader=validation_loader, log=log)

Cosine Annealing


  0%|          | 1/300 [00:00<?, ?it/s]

[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 1 metrics: {'accuracy': 0.2164, 'crossentropy': 2.1492774982452394}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 2 metrics: {'accuracy': 0.2372, 'crossentropy': 1.9290581993103026}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 3 metrics: {'accuracy': 0.2882, 'crossentropy': 1.8837613988876343}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 4 metrics: {'accuracy': 0.2794, 'crossentropy': 2.0415959819793703}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 5 metrics: {'accuracy': 0.3364, 'crossentropy': 1.7633274457931518}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 6 metrics: {'accuracy': 0.3352, 'crossentropy': 1.8306858547210694}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 7 metrics: {'accuracy': 0.3744, 'crossentropy': 1.675206308555603}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 8 metrics: {'accuracy': 0.391, 'crossentropy': 1.6241544921875}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 9 metrics: {'accuracy': 0.4128, 'crossentropy': 1.6204852634429932}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 10 metrics: {'accuracy': 0.3924, 'crossentropy': 1.8160644733428954}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 11 metrics: {'accuracy': 0.4326, 'crossentropy': 1.6231806396484374}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 12 metrics: {'accuracy': 0.4442, 'crossentropy': 1.5932003860473634}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 13 metrics: {'accuracy': 0.4844, 'crossentropy': 1.4626072359085083}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 14 metrics: {'accuracy': 0.4606, 'crossentropy': 1.6034251977920533}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 15 metrics: {'accuracy': 0.485, 'crossentropy': 1.4774507816314697}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 16 metrics: {'accuracy': 0.5332, 'crossentropy': 1.3882559200286866}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 17 metrics: {'accuracy': 0.4782, 'crossentropy': 1.6575186491012572}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 18 metrics: {'accuracy': 0.4776, 'crossentropy': 1.5798493549346924}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 19 metrics: {'accuracy': 0.5468, 'crossentropy': 1.3278626495361328}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 20 metrics: {'accuracy': 0.5158, 'crossentropy': 1.486465266418457}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 21 metrics: {'accuracy': 0.5556, 'crossentropy': 1.3565663835525512}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 22 metrics: {'accuracy': 0.5378, 'crossentropy': 1.4065797653198242}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 23 metrics: {'accuracy': 0.5392, 'crossentropy': 1.554705366897583}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 24 metrics: {'accuracy': 0.519, 'crossentropy': 1.5612750759124756}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 25 metrics: {'accuracy': 0.5714, 'crossentropy': 1.4186917364120484}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 26 metrics: {'accuracy': 0.5642, 'crossentropy': 1.4817778198242189}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 27 metrics: {'accuracy': 0.5726, 'crossentropy': 1.3985243167877197}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 28 metrics: {'accuracy': 0.5534, 'crossentropy': 1.4795425735473633}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 29 metrics: {'accuracy': 0.5862, 'crossentropy': 1.2989042516708373}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 30 metrics: {'accuracy': 0.6064, 'crossentropy': 1.3191610109329224}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 31 metrics: {'accuracy': 0.595, 'crossentropy': 1.3418997720718384}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 32 metrics: {'accuracy': 0.5756, 'crossentropy': 1.4530495958328247}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 33 metrics: {'accuracy': 0.5842, 'crossentropy': 1.661891321182251}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 34 metrics: {'accuracy': 0.6206, 'crossentropy': 1.2836292247772216}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 35 metrics: {'accuracy': 0.5882, 'crossentropy': 1.3914262773513795}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 36 metrics: {'accuracy': 0.5902, 'crossentropy': 1.492536619567871}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 37 metrics: {'accuracy': 0.572, 'crossentropy': 1.5827240232467652}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 38 metrics: {'accuracy': 0.5958, 'crossentropy': 1.6376944299697875}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 39 metrics: {'accuracy': 0.5614, 'crossentropy': 1.755116641998291}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 40 metrics: {'accuracy': 0.6226, 'crossentropy': 1.4571272537231446}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 41 metrics: {'accuracy': 0.6134, 'crossentropy': 1.4448774215698241}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 42 metrics: {'accuracy': 0.5778, 'crossentropy': 1.5845903659820557}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 43 metrics: {'accuracy': 0.6396, 'crossentropy': 1.338677777671814}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 44 metrics: {'accuracy': 0.63, 'crossentropy': 1.430566248512268}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 45 metrics: {'accuracy': 0.6302, 'crossentropy': 1.5538471431732177}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 46 metrics: {'accuracy': 0.6282, 'crossentropy': 1.5694222000122071}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 47 metrics: {'accuracy': 0.61, 'crossentropy': 1.6805202793121339}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 48 metrics: {'accuracy': 0.6284, 'crossentropy': 1.4869282711029053}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 49 metrics: {'accuracy': 0.6432, 'crossentropy': 1.4181401374816895}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 50 metrics: {'accuracy': 0.6162, 'crossentropy': 1.5683718784332275}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 51 metrics: {'accuracy': 0.6616, 'crossentropy': 1.363122608947754}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 52 metrics: {'accuracy': 0.652, 'crossentropy': 1.4454259424209595}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 53 metrics: {'accuracy': 0.6806, 'crossentropy': 1.336198017501831}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 54 metrics: {'accuracy': 0.6792, 'crossentropy': 1.2796468240737915}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 55 metrics: {'accuracy': 0.6796, 'crossentropy': 1.3375492029190064}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 56 metrics: {'accuracy': 0.655, 'crossentropy': 1.534458289337158}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 57 metrics: {'accuracy': 0.6702, 'crossentropy': 1.5365722450256347}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 58 metrics: {'accuracy': 0.6636, 'crossentropy': 1.4429270286560059}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 59 metrics: {'accuracy': 0.6896, 'crossentropy': 1.4279500259399414}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 60 metrics: {'accuracy': 0.6104, 'crossentropy': 2.047204118728638}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 61 metrics: {'accuracy': 0.6426, 'crossentropy': 1.700003238105774}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 62 metrics: {'accuracy': 0.6498, 'crossentropy': 1.7223677753448485}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 63 metrics: {'accuracy': 0.674, 'crossentropy': 1.568129213142395}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 64 metrics: {'accuracy': 0.679, 'crossentropy': 1.5233797443389892}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 65 metrics: {'accuracy': 0.6556, 'crossentropy': 1.5988889015197754}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 66 metrics: {'accuracy': 0.681, 'crossentropy': 1.5559561515808105}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 67 metrics: {'accuracy': 0.6558, 'crossentropy': 1.5861485748291015}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 68 metrics: {'accuracy': 0.6684, 'crossentropy': 1.6005359226226807}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 69 metrics: {'accuracy': 0.683, 'crossentropy': 1.556698197364807}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 70 metrics: {'accuracy': 0.666, 'crossentropy': 1.8341962125778197}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 71 metrics: {'accuracy': 0.6646, 'crossentropy': 1.7240430130004882}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 72 metrics: {'accuracy': 0.6864, 'crossentropy': 1.688390433883667}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 73 metrics: {'accuracy': 0.6898, 'crossentropy': 1.4424149753570557}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 74 metrics: {'accuracy': 0.6784, 'crossentropy': 1.5320212787628174}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 75 metrics: {'accuracy': 0.6572, 'crossentropy': 1.9239155548095703}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 76 metrics: {'accuracy': 0.6994, 'crossentropy': 1.503293971633911}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 77 metrics: {'accuracy': 0.6802, 'crossentropy': 1.7182488130569458}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 78 metrics: {'accuracy': 0.6624, 'crossentropy': 2.040979455757141}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 79 metrics: {'accuracy': 0.7108, 'crossentropy': 1.5265844261169434}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 80 metrics: {'accuracy': 0.639, 'crossentropy': 2.047646946144104}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 81 metrics: {'accuracy': 0.697, 'crossentropy': 1.5622214616775512}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 82 metrics: {'accuracy': 0.6968, 'crossentropy': 1.747803352355957}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 83 metrics: {'accuracy': 0.664, 'crossentropy': 1.9821340461730956}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 84 metrics: {'accuracy': 0.679, 'crossentropy': 1.7599634023666382}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 85 metrics: {'accuracy': 0.6754, 'crossentropy': 1.7645211408615111}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 86 metrics: {'accuracy': 0.6918, 'crossentropy': 1.7371683568954468}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 87 metrics: {'accuracy': 0.6808, 'crossentropy': 1.8495920518875122}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 88 metrics: {'accuracy': 0.7046, 'crossentropy': 1.6057298624038696}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 89 metrics: {'accuracy': 0.7, 'crossentropy': 1.5827246383666993}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 90 metrics: {'accuracy': 0.7134, 'crossentropy': 1.6326092628479003}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 91 metrics: {'accuracy': 0.689, 'crossentropy': 1.8398972099304198}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 92 metrics: {'accuracy': 0.6988, 'crossentropy': 1.703945962524414}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 93 metrics: {'accuracy': 0.6928, 'crossentropy': 1.8319120206832886}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 94 metrics: {'accuracy': 0.6742, 'crossentropy': 1.9307451648712157}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 95 metrics: {'accuracy': 0.6652, 'crossentropy': 1.9839211711883544}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 96 metrics: {'accuracy': 0.7014, 'crossentropy': 1.753114981651306}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 97 metrics: {'accuracy': 0.7168, 'crossentropy': 1.583624532699585}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 98 metrics: {'accuracy': 0.7178, 'crossentropy': 1.5080754125595093}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 99 metrics: {'accuracy': 0.7008, 'crossentropy': 1.691151003074646}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 100 metrics: {'accuracy': 0.7082, 'crossentropy': 1.786831614112854}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 101 metrics: {'accuracy': 0.7048, 'crossentropy': 1.8026102556228638}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 102 metrics: {'accuracy': 0.7088, 'crossentropy': 1.778138516998291}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 103 metrics: {'accuracy': 0.7074, 'crossentropy': 1.7982812139511108}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 104 metrics: {'accuracy': 0.699, 'crossentropy': 1.975844974899292}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 105 metrics: {'accuracy': 0.719, 'crossentropy': 1.7399523822784424}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 106 metrics: {'accuracy': 0.6984, 'crossentropy': 1.851081118774414}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 107 metrics: {'accuracy': 0.7116, 'crossentropy': 1.8264789319992065}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 108 metrics: {'accuracy': 0.7048, 'crossentropy': 1.852280344581604}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 109 metrics: {'accuracy': 0.7158, 'crossentropy': 1.6651891231536866}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 110 metrics: {'accuracy': 0.7026, 'crossentropy': 1.9465272687911988}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 111 metrics: {'accuracy': 0.7, 'crossentropy': 1.869952957725525}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 112 metrics: {'accuracy': 0.7044, 'crossentropy': 1.903688197517395}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 113 metrics: {'accuracy': 0.711, 'crossentropy': 1.826317674446106}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 114 metrics: {'accuracy': 0.7004, 'crossentropy': 1.98455932598114}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 115 metrics: {'accuracy': 0.7118, 'crossentropy': 1.847875990486145}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 116 metrics: {'accuracy': 0.7208, 'crossentropy': 1.6717159650802613}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 117 metrics: {'accuracy': 0.723, 'crossentropy': 1.768020641708374}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 118 metrics: {'accuracy': 0.726, 'crossentropy': 1.7357866855621338}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 119 metrics: {'accuracy': 0.7172, 'crossentropy': 1.8671522586822509}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 120 metrics: {'accuracy': 0.7108, 'crossentropy': 1.839890744972229}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 121 metrics: {'accuracy': 0.7262, 'crossentropy': 1.7940632837295531}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 122 metrics: {'accuracy': 0.7254, 'crossentropy': 1.739738676071167}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 123 metrics: {'accuracy': 0.7354, 'crossentropy': 1.7203208097457885}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 124 metrics: {'accuracy': 0.6992, 'crossentropy': 2.108544366455078}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 125 metrics: {'accuracy': 0.727, 'crossentropy': 1.7606943075180053}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 126 metrics: {'accuracy': 0.736, 'crossentropy': 1.6882964929580688}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 127 metrics: {'accuracy': 0.7374, 'crossentropy': 1.7407338274002075}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 128 metrics: {'accuracy': 0.7314, 'crossentropy': 1.760880549621582}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 129 metrics: {'accuracy': 0.7208, 'crossentropy': 1.8498917400360106}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 130 metrics: {'accuracy': 0.7208, 'crossentropy': 1.8959340000152587}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 131 metrics: {'accuracy': 0.7142, 'crossentropy': 2.0124451528549194}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 132 metrics: {'accuracy': 0.7232, 'crossentropy': 1.9201104499816894}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 133 metrics: {'accuracy': 0.7304, 'crossentropy': 1.8375703491210937}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 134 metrics: {'accuracy': 0.7116, 'crossentropy': 2.088616641998291}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 135 metrics: {'accuracy': 0.7184, 'crossentropy': 1.978208535194397}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 136 metrics: {'accuracy': 0.7208, 'crossentropy': 1.8705389200210571}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 137 metrics: {'accuracy': 0.7178, 'crossentropy': 1.8655729164123536}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 138 metrics: {'accuracy': 0.7346, 'crossentropy': 1.8156576793670653}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 139 metrics: {'accuracy': 0.7268, 'crossentropy': 1.9502580039978028}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 140 metrics: {'accuracy': 0.7266, 'crossentropy': 1.8996942594528199}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 141 metrics: {'accuracy': 0.731, 'crossentropy': 1.7910018768310547}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 142 metrics: {'accuracy': 0.7302, 'crossentropy': 1.8320497930526733}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 143 metrics: {'accuracy': 0.7412, 'crossentropy': 1.6873140272140503}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 144 metrics: {'accuracy': 0.7404, 'crossentropy': 1.7187595129013062}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 145 metrics: {'accuracy': 0.741, 'crossentropy': 1.7379650772094726}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 146 metrics: {'accuracy': 0.7342, 'crossentropy': 1.7737857412338256}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 147 metrics: {'accuracy': 0.736, 'crossentropy': 1.828852554321289}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 148 metrics: {'accuracy': 0.7372, 'crossentropy': 1.7541490106582642}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 149 metrics: {'accuracy': 0.7304, 'crossentropy': 1.9460332218170167}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 150 metrics: {'accuracy': 0.742, 'crossentropy': 1.8300790777206422}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 151 metrics: {'accuracy': 0.742, 'crossentropy': 1.7707745203018188}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 152 metrics: {'accuracy': 0.7442, 'crossentropy': 1.7096362951278687}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 153 metrics: {'accuracy': 0.7482, 'crossentropy': 1.7197347803115846}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 154 metrics: {'accuracy': 0.7404, 'crossentropy': 1.8146707033157348}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 155 metrics: {'accuracy': 0.7466, 'crossentropy': 1.689366346168518}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 156 metrics: {'accuracy': 0.7484, 'crossentropy': 1.76810826587677}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 157 metrics: {'accuracy': 0.744, 'crossentropy': 1.7717388998031616}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 158 metrics: {'accuracy': 0.7396, 'crossentropy': 1.7943604690551758}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 159 metrics: {'accuracy': 0.7418, 'crossentropy': 1.8290934688568115}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 160 metrics: {'accuracy': 0.7444, 'crossentropy': 1.7629362171173095}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 161 metrics: {'accuracy': 0.744, 'crossentropy': 1.8049781238555909}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 162 metrics: {'accuracy': 0.7504, 'crossentropy': 1.7380799936294555}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 163 metrics: {'accuracy': 0.751, 'crossentropy': 1.776394571685791}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 164 metrics: {'accuracy': 0.7538, 'crossentropy': 1.7701518190383911}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 165 metrics: {'accuracy': 0.7462, 'crossentropy': 1.7895368011474608}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 166 metrics: {'accuracy': 0.7454, 'crossentropy': 1.806629451942444}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 167 metrics: {'accuracy': 0.7514, 'crossentropy': 1.747896582221985}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 168 metrics: {'accuracy': 0.747, 'crossentropy': 1.7956759510040283}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 169 metrics: {'accuracy': 0.7448, 'crossentropy': 1.7847340812683106}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 170 metrics: {'accuracy': 0.7434, 'crossentropy': 1.7952884168624879}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 171 metrics: {'accuracy': 0.7376, 'crossentropy': 1.850986799621582}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 172 metrics: {'accuracy': 0.747, 'crossentropy': 1.7756878700256347}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 173 metrics: {'accuracy': 0.7438, 'crossentropy': 1.8509971067428588}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 174 metrics: {'accuracy': 0.742, 'crossentropy': 1.8420905973434447}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 175 metrics: {'accuracy': 0.7412, 'crossentropy': 1.8683632846832274}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 176 metrics: {'accuracy': 0.7512, 'crossentropy': 1.7546294881820679}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 177 metrics: {'accuracy': 0.7498, 'crossentropy': 1.8416410556793212}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 178 metrics: {'accuracy': 0.7514, 'crossentropy': 1.753549331855774}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 179 metrics: {'accuracy': 0.749, 'crossentropy': 1.7738783197402954}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 180 metrics: {'accuracy': 0.7454, 'crossentropy': 1.8118638408660888}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 181 metrics: {'accuracy': 0.7476, 'crossentropy': 1.7813485111236573}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 182 metrics: {'accuracy': 0.746, 'crossentropy': 1.8107934679031372}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 183 metrics: {'accuracy': 0.7448, 'crossentropy': 1.831620743751526}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 184 metrics: {'accuracy': 0.745, 'crossentropy': 1.789025442123413}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 185 metrics: {'accuracy': 0.7458, 'crossentropy': 1.8282613931655884}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 186 metrics: {'accuracy': 0.7496, 'crossentropy': 1.735549228477478}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 187 metrics: {'accuracy': 0.7518, 'crossentropy': 1.751326756286621}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 188 metrics: {'accuracy': 0.7498, 'crossentropy': 1.7462286001205445}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 189 metrics: {'accuracy': 0.7462, 'crossentropy': 1.7955290658950807}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 190 metrics: {'accuracy': 0.7526, 'crossentropy': 1.7689809701919557}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 191 metrics: {'accuracy': 0.7498, 'crossentropy': 1.7410721433639527}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 192 metrics: {'accuracy': 0.7478, 'crossentropy': 1.7681575706481933}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 193 metrics: {'accuracy': 0.7484, 'crossentropy': 1.7971847404479981}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 194 metrics: {'accuracy': 0.7504, 'crossentropy': 1.781201608276367}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 195 metrics: {'accuracy': 0.7498, 'crossentropy': 1.7511244403839112}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 196 metrics: {'accuracy': 0.7538, 'crossentropy': 1.7446035387039185}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 197 metrics: {'accuracy': 0.749, 'crossentropy': 1.7559877395629884}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 198 metrics: {'accuracy': 0.7482, 'crossentropy': 1.7675554174423218}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 199 metrics: {'accuracy': 0.7536, 'crossentropy': 1.758990524482727}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 200 metrics: {'accuracy': 0.7506, 'crossentropy': 1.7426933135986329}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 201 metrics: {'accuracy': 0.75, 'crossentropy': 1.75348480052948}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 202 metrics: {'accuracy': 0.748, 'crossentropy': 1.7537748149871826}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 203 metrics: {'accuracy': 0.7496, 'crossentropy': 1.7738485204696655}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 204 metrics: {'accuracy': 0.7532, 'crossentropy': 1.7541701692581178}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 205 metrics: {'accuracy': 0.7498, 'crossentropy': 1.7663930812835693}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 206 metrics: {'accuracy': 0.749, 'crossentropy': 1.7786988178253174}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 207 metrics: {'accuracy': 0.7526, 'crossentropy': 1.7437051475524903}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 208 metrics: {'accuracy': 0.7538, 'crossentropy': 1.7248931865692139}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 209 metrics: {'accuracy': 0.7544, 'crossentropy': 1.71589019947052}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 210 metrics: {'accuracy': 0.7516, 'crossentropy': 1.758341605758667}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 211 metrics: {'accuracy': 0.756, 'crossentropy': 1.741941227722168}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 212 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7454945798873902}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 213 metrics: {'accuracy': 0.757, 'crossentropy': 1.7174640022277832}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 214 metrics: {'accuracy': 0.7574, 'crossentropy': 1.7383282976150514}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 215 metrics: {'accuracy': 0.7608, 'crossentropy': 1.7221782392501832}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 216 metrics: {'accuracy': 0.7552, 'crossentropy': 1.7076754961013794}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 217 metrics: {'accuracy': 0.7542, 'crossentropy': 1.7182720067977906}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 218 metrics: {'accuracy': 0.7578, 'crossentropy': 1.6952446559906005}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 219 metrics: {'accuracy': 0.7554, 'crossentropy': 1.7280960943222046}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 220 metrics: {'accuracy': 0.755, 'crossentropy': 1.7495066160202026}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 221 metrics: {'accuracy': 0.7572, 'crossentropy': 1.7330620851516723}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 222 metrics: {'accuracy': 0.759, 'crossentropy': 1.7078282203674315}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 223 metrics: {'accuracy': 0.7608, 'crossentropy': 1.7290487628936768}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 224 metrics: {'accuracy': 0.7572, 'crossentropy': 1.7303240739822388}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 225 metrics: {'accuracy': 0.7582, 'crossentropy': 1.717389938735962}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 226 metrics: {'accuracy': 0.7556, 'crossentropy': 1.7268558807373047}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 227 metrics: {'accuracy': 0.7586, 'crossentropy': 1.7337241804122925}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 228 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7270678817749023}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 229 metrics: {'accuracy': 0.7576, 'crossentropy': 1.7182663452148437}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 230 metrics: {'accuracy': 0.7576, 'crossentropy': 1.7021702903747558}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 231 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7144253566741943}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 232 metrics: {'accuracy': 0.7566, 'crossentropy': 1.7321986429214478}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 233 metrics: {'accuracy': 0.7566, 'crossentropy': 1.7183519495010375}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 234 metrics: {'accuracy': 0.7552, 'crossentropy': 1.7462016277313233}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 235 metrics: {'accuracy': 0.7556, 'crossentropy': 1.7180176303863526}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 236 metrics: {'accuracy': 0.757, 'crossentropy': 1.7254634140014649}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 237 metrics: {'accuracy': 0.7556, 'crossentropy': 1.7285911252975463}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 238 metrics: {'accuracy': 0.7574, 'crossentropy': 1.683826693725586}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 239 metrics: {'accuracy': 0.7566, 'crossentropy': 1.7150617109298707}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 240 metrics: {'accuracy': 0.7544, 'crossentropy': 1.7322680219650268}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 241 metrics: {'accuracy': 0.755, 'crossentropy': 1.7005619104385377}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 242 metrics: {'accuracy': 0.756, 'crossentropy': 1.7127049654006958}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 243 metrics: {'accuracy': 0.7546, 'crossentropy': 1.7187364250183106}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 244 metrics: {'accuracy': 0.7562, 'crossentropy': 1.6745201164245604}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 245 metrics: {'accuracy': 0.7558, 'crossentropy': 1.726686424255371}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 246 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7162207075119018}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 247 metrics: {'accuracy': 0.7548, 'crossentropy': 1.7088313955307006}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 248 metrics: {'accuracy': 0.755, 'crossentropy': 1.7047726398468017}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 249 metrics: {'accuracy': 0.7558, 'crossentropy': 1.700604621887207}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 250 metrics: {'accuracy': 0.7548, 'crossentropy': 1.715393025779724}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 251 metrics: {'accuracy': 0.7564, 'crossentropy': 1.7037671222686768}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 252 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7186790084838868}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 253 metrics: {'accuracy': 0.7568, 'crossentropy': 1.7143670669555664}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 254 metrics: {'accuracy': 0.7552, 'crossentropy': 1.6969462743759156}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 255 metrics: {'accuracy': 0.7568, 'crossentropy': 1.7325983026504517}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 256 metrics: {'accuracy': 0.7558, 'crossentropy': 1.7111919023513793}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 257 metrics: {'accuracy': 0.7532, 'crossentropy': 1.6999373943328857}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 258 metrics: {'accuracy': 0.7542, 'crossentropy': 1.7167243534088135}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 259 metrics: {'accuracy': 0.7566, 'crossentropy': 1.70211136302948}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 260 metrics: {'accuracy': 0.756, 'crossentropy': 1.7309243520736695}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 261 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7007623559951783}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 262 metrics: {'accuracy': 0.7532, 'crossentropy': 1.7180386194229127}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 263 metrics: {'accuracy': 0.7546, 'crossentropy': 1.7187950462341308}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 264 metrics: {'accuracy': 0.7536, 'crossentropy': 1.7222141962051392}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 265 metrics: {'accuracy': 0.7564, 'crossentropy': 1.6984967140197753}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 266 metrics: {'accuracy': 0.7558, 'crossentropy': 1.703884732055664}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 267 metrics: {'accuracy': 0.7548, 'crossentropy': 1.7002727746963502}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 268 metrics: {'accuracy': 0.7554, 'crossentropy': 1.7004230436325074}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 269 metrics: {'accuracy': 0.7566, 'crossentropy': 1.6978841403961182}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 270 metrics: {'accuracy': 0.7558, 'crossentropy': 1.6998144533157349}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 271 metrics: {'accuracy': 0.756, 'crossentropy': 1.7053843914031983}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 272 metrics: {'accuracy': 0.7524, 'crossentropy': 1.7117718711853027}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 273 metrics: {'accuracy': 0.7552, 'crossentropy': 1.708799320411682}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 274 metrics: {'accuracy': 0.755, 'crossentropy': 1.6985661289215088}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 275 metrics: {'accuracy': 0.7556, 'crossentropy': 1.7029306161880493}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 276 metrics: {'accuracy': 0.7516, 'crossentropy': 1.7356026754379272}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 277 metrics: {'accuracy': 0.758, 'crossentropy': 1.7030886268615724}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 278 metrics: {'accuracy': 0.7542, 'crossentropy': 1.7299008548736572}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 279 metrics: {'accuracy': 0.7552, 'crossentropy': 1.6949047395706176}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 280 metrics: {'accuracy': 0.7574, 'crossentropy': 1.7116279424667358}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 281 metrics: {'accuracy': 0.7536, 'crossentropy': 1.7003714113235473}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 282 metrics: {'accuracy': 0.7542, 'crossentropy': 1.6931275115966797}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 283 metrics: {'accuracy': 0.7534, 'crossentropy': 1.6780114456176758}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 284 metrics: {'accuracy': 0.7548, 'crossentropy': 1.7185584741592408}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 285 metrics: {'accuracy': 0.7536, 'crossentropy': 1.7136097019195558}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 286 metrics: {'accuracy': 0.756, 'crossentropy': 1.6972362438201904}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 287 metrics: {'accuracy': 0.755, 'crossentropy': 1.714221834564209}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 288 metrics: {'accuracy': 0.7568, 'crossentropy': 1.67931552734375}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 289 metrics: {'accuracy': 0.7548, 'crossentropy': 1.7092952177047729}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 290 metrics: {'accuracy': 0.7564, 'crossentropy': 1.7008082876205444}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 291 metrics: {'accuracy': 0.7558, 'crossentropy': 1.6882962390899658}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 292 metrics: {'accuracy': 0.7552, 'crossentropy': 1.6931142219543458}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 293 metrics: {'accuracy': 0.7556, 'crossentropy': 1.7219937639236451}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 294 metrics: {'accuracy': 0.7542, 'crossentropy': 1.7356434558868408}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 295 metrics: {'accuracy': 0.7552, 'crossentropy': 1.7052037885665894}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 296 metrics: {'accuracy': 0.7542, 'crossentropy': 1.7217666845321655}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 297 metrics: {'accuracy': 0.7544, 'crossentropy': 1.7073020112991333}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 298 metrics: {'accuracy': 0.7562, 'crossentropy': 1.7094356815338134}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 299 metrics: {'accuracy': 0.7534, 'crossentropy': 1.7303889541625976}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 300 metrics: {'accuracy': 0.756, 'crossentropy': 1.704508249282837}


In [ ]:
# experiment

evaluate(model=trained_model, num_samples=50, loader=test_loader, device="cuda")

get_predictions_labels:   0%|          | 0/500000 [00:00<?, ?it/s]

{'accuracy': 0.7593, 'crossentropy': tensor(1.3171)}

In [ ]:
# experiment

from torch.utils import data

model_trainer = Cifar10ModelTrainer(device="cuda")

train_loader = model_trainer.get_train_dataloader(split_dataset.train * 0.06)
validation_loader = model_trainer.get_evaluation_dataloader(split_dataset.validation)
test_loader = model_trainer.get_evaluation_dataloader(split_dataset.test)

log = {}
trained_model = model_trainer.get_trained(train_loader=train_loader, train_augmentations=split_dataset.train_augmentations, validation_loader=validation_loader, log=log)

Cosine Annealing


  0%|          | 1/300 [00:00<?, ?it/s]

[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 1 metrics: {'accuracy': 0.195, 'crossentropy': 2.2275007415771486}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 2 metrics: {'accuracy': 0.2544, 'crossentropy': 1.9551373893737793}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 3 metrics: {'accuracy': 0.2624, 'crossentropy': 1.9743153453826905}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 4 metrics: {'accuracy': 0.3196, 'crossentropy': 1.793511326980591}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 5 metrics: {'accuracy': 0.3322, 'crossentropy': 1.7936479278564452}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 6 metrics: {'accuracy': 0.3802, 'crossentropy': 1.6548445222854615}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 7 metrics: {'accuracy': 0.397, 'crossentropy': 1.6764303909301759}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 8 metrics: {'accuracy': 0.402, 'crossentropy': 1.6659705043792725}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 9 metrics: {'accuracy': 0.4102, 'crossentropy': 1.6029461530685425}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 10 metrics: {'accuracy': 0.4536, 'crossentropy': 1.5197191888809205}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 11 metrics: {'accuracy': 0.4498, 'crossentropy': 1.526081286239624}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 12 metrics: {'accuracy': 0.4644, 'crossentropy': 1.6233149143218994}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 13 metrics: {'accuracy': 0.484, 'crossentropy': 1.5035313310623168}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 14 metrics: {'accuracy': 0.4802, 'crossentropy': 1.5805600301742553}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 15 metrics: {'accuracy': 0.4802, 'crossentropy': 1.6135048929214477}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 16 metrics: {'accuracy': 0.5, 'crossentropy': 1.7078393663406373}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 17 metrics: {'accuracy': 0.4758, 'crossentropy': 1.7879548362731934}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 18 metrics: {'accuracy': 0.5334, 'crossentropy': 1.4923369665145874}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 19 metrics: {'accuracy': 0.4754, 'crossentropy': 1.7693965662002564}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 20 metrics: {'accuracy': 0.5038, 'crossentropy': 1.625737899017334}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 21 metrics: {'accuracy': 0.5378, 'crossentropy': 1.4750005517959595}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 22 metrics: {'accuracy': 0.5364, 'crossentropy': 1.7414169107437134}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 23 metrics: {'accuracy': 0.5634, 'crossentropy': 1.4580804355621337}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 24 metrics: {'accuracy': 0.5646, 'crossentropy': 1.5308198135375977}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 25 metrics: {'accuracy': 0.544, 'crossentropy': 1.6010465715408326}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 26 metrics: {'accuracy': 0.4906, 'crossentropy': 2.484989644622803}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 27 metrics: {'accuracy': 0.5444, 'crossentropy': 1.7441176502227784}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 28 metrics: {'accuracy': 0.5734, 'crossentropy': 1.5949208166122437}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 29 metrics: {'accuracy': 0.547, 'crossentropy': 1.9925661281585694}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 30 metrics: {'accuracy': 0.5416, 'crossentropy': 1.677072798538208}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 31 metrics: {'accuracy': 0.58, 'crossentropy': 1.6823016321182251}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 32 metrics: {'accuracy': 0.5624, 'crossentropy': 1.7964260828018188}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 33 metrics: {'accuracy': 0.5872, 'crossentropy': 1.5960037258148194}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 34 metrics: {'accuracy': 0.5884, 'crossentropy': 1.8452243558883668}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 35 metrics: {'accuracy': 0.5226, 'crossentropy': 2.390915496826172}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 36 metrics: {'accuracy': 0.5862, 'crossentropy': 1.751786165046692}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 37 metrics: {'accuracy': 0.5546, 'crossentropy': 2.283739311981201}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 38 metrics: {'accuracy': 0.6002, 'crossentropy': 1.8924382423400878}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 39 metrics: {'accuracy': 0.6044, 'crossentropy': 1.843834720993042}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 40 metrics: {'accuracy': 0.557, 'crossentropy': 2.5205303379058837}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 41 metrics: {'accuracy': 0.6, 'crossentropy': 2.0484943454742433}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 42 metrics: {'accuracy': 0.5678, 'crossentropy': 2.2353332565307618}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 43 metrics: {'accuracy': 0.6056, 'crossentropy': 1.9236523778915404}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 44 metrics: {'accuracy': 0.6086, 'crossentropy': 2.0088993383407594}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 45 metrics: {'accuracy': 0.5854, 'crossentropy': 2.0999632850646974}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 46 metrics: {'accuracy': 0.6124, 'crossentropy': 2.0430711101531984}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 47 metrics: {'accuracy': 0.5824, 'crossentropy': 2.463464071273804}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 48 metrics: {'accuracy': 0.5152, 'crossentropy': 3.106986325073242}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 49 metrics: {'accuracy': 0.5628, 'crossentropy': 3.0276481426239013}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 50 metrics: {'accuracy': 0.5918, 'crossentropy': 2.4354282920837402}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 51 metrics: {'accuracy': 0.6016, 'crossentropy': 2.4161296077728274}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 52 metrics: {'accuracy': 0.6054, 'crossentropy': 2.1799372734069826}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 53 metrics: {'accuracy': 0.6186, 'crossentropy': 2.320051356124878}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 54 metrics: {'accuracy': 0.6206, 'crossentropy': 2.2799232097625732}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 55 metrics: {'accuracy': 0.5348, 'crossentropy': 3.0492108322143556}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 56 metrics: {'accuracy': 0.6016, 'crossentropy': 2.4531355388641356}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 57 metrics: {'accuracy': 0.551, 'crossentropy': 3.044118001174927}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 58 metrics: {'accuracy': 0.603, 'crossentropy': 2.3964352600097656}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 59 metrics: {'accuracy': 0.6266, 'crossentropy': 2.265823505783081}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 60 metrics: {'accuracy': 0.5736, 'crossentropy': 2.7588639423370362}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 61 metrics: {'accuracy': 0.5724, 'crossentropy': 3.2521114952087404}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 62 metrics: {'accuracy': 0.6122, 'crossentropy': 2.504523838043213}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 63 metrics: {'accuracy': 0.6152, 'crossentropy': 2.3536159328460693}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 64 metrics: {'accuracy': 0.6342, 'crossentropy': 2.0525430145263672}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 65 metrics: {'accuracy': 0.5866, 'crossentropy': 2.92167788772583}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 66 metrics: {'accuracy': 0.6068, 'crossentropy': 2.8618898265838624}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 67 metrics: {'accuracy': 0.617, 'crossentropy': 2.496814747238159}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 68 metrics: {'accuracy': 0.6126, 'crossentropy': 2.672058623123169}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 69 metrics: {'accuracy': 0.6252, 'crossentropy': 2.4534772537231446}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 70 metrics: {'accuracy': 0.606, 'crossentropy': 2.6408395263671873}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 71 metrics: {'accuracy': 0.6114, 'crossentropy': 2.454712201309204}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 72 metrics: {'accuracy': 0.6094, 'crossentropy': 2.6132784965515135}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 73 metrics: {'accuracy': 0.6212, 'crossentropy': 2.4521360389709472}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 74 metrics: {'accuracy': 0.6124, 'crossentropy': 2.5769725296020507}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 75 metrics: {'accuracy': 0.645, 'crossentropy': 2.324598404312134}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 76 metrics: {'accuracy': 0.587, 'crossentropy': 2.565751948928833}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 77 metrics: {'accuracy': 0.6134, 'crossentropy': 2.442854005050659}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 78 metrics: {'accuracy': 0.6374, 'crossentropy': 2.322680012893677}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 79 metrics: {'accuracy': 0.6328, 'crossentropy': 2.522608646774292}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 80 metrics: {'accuracy': 0.643, 'crossentropy': 2.56666565322876}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 81 metrics: {'accuracy': 0.6378, 'crossentropy': 2.55048551902771}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 82 metrics: {'accuracy': 0.6262, 'crossentropy': 2.5220425621032714}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 83 metrics: {'accuracy': 0.6482, 'crossentropy': 2.3307431190490724}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 84 metrics: {'accuracy': 0.6428, 'crossentropy': 2.538757446670532}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 85 metrics: {'accuracy': 0.653, 'crossentropy': 2.531304301071167}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 86 metrics: {'accuracy': 0.6514, 'crossentropy': 2.4802711391448975}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 87 metrics: {'accuracy': 0.6408, 'crossentropy': 2.519509112930298}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 88 metrics: {'accuracy': 0.6302, 'crossentropy': 2.8033425285339355}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 89 metrics: {'accuracy': 0.5906, 'crossentropy': 3.1088540802001954}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 90 metrics: {'accuracy': 0.6518, 'crossentropy': 2.364090956878662}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 91 metrics: {'accuracy': 0.649, 'crossentropy': 2.437061553955078}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 92 metrics: {'accuracy': 0.6098, 'crossentropy': 2.992073026275635}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 93 metrics: {'accuracy': 0.6298, 'crossentropy': 2.565552684020996}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 94 metrics: {'accuracy': 0.632, 'crossentropy': 2.482003544616699}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 95 metrics: {'accuracy': 0.6386, 'crossentropy': 2.474025467300415}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 96 metrics: {'accuracy': 0.6198, 'crossentropy': 2.7246614974975585}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 97 metrics: {'accuracy': 0.6288, 'crossentropy': 2.563767330932617}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 98 metrics: {'accuracy': 0.6334, 'crossentropy': 2.4633625190734865}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 99 metrics: {'accuracy': 0.6444, 'crossentropy': 2.4796057315826414}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 100 metrics: {'accuracy': 0.6602, 'crossentropy': 2.3063468326568604}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 101 metrics: {'accuracy': 0.6418, 'crossentropy': 2.6951640800476073}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 102 metrics: {'accuracy': 0.659, 'crossentropy': 2.5758142349243163}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 103 metrics: {'accuracy': 0.6398, 'crossentropy': 2.6922632511138915}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 104 metrics: {'accuracy': 0.65, 'crossentropy': 2.513911172866821}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 105 metrics: {'accuracy': 0.6348, 'crossentropy': 2.892625143814087}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 106 metrics: {'accuracy': 0.6426, 'crossentropy': 2.7528413955688475}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 107 metrics: {'accuracy': 0.6386, 'crossentropy': 2.7084561500549316}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 108 metrics: {'accuracy': 0.6522, 'crossentropy': 2.6051291774749754}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 109 metrics: {'accuracy': 0.6592, 'crossentropy': 2.4843068431854247}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 110 metrics: {'accuracy': 0.6586, 'crossentropy': 2.4939362491607664}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 111 metrics: {'accuracy': 0.655, 'crossentropy': 2.613300040435791}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 112 metrics: {'accuracy': 0.6512, 'crossentropy': 2.637877791595459}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 113 metrics: {'accuracy': 0.6398, 'crossentropy': 2.7666606281280517}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 114 metrics: {'accuracy': 0.641, 'crossentropy': 2.64063610458374}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 115 metrics: {'accuracy': 0.636, 'crossentropy': 2.971825}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 116 metrics: {'accuracy': 0.6508, 'crossentropy': 2.697191888809204}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 117 metrics: {'accuracy': 0.6586, 'crossentropy': 2.843339631652832}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 118 metrics: {'accuracy': 0.6452, 'crossentropy': 2.714418073272705}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 119 metrics: {'accuracy': 0.6432, 'crossentropy': 2.867455952835083}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 120 metrics: {'accuracy': 0.6438, 'crossentropy': 2.6972543994903564}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 121 metrics: {'accuracy': 0.6538, 'crossentropy': 2.5744204502105714}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 122 metrics: {'accuracy': 0.6558, 'crossentropy': 2.515961482620239}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 123 metrics: {'accuracy': 0.6554, 'crossentropy': 2.6600591705322265}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 124 metrics: {'accuracy': 0.6532, 'crossentropy': 2.7306379859924315}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 125 metrics: {'accuracy': 0.6576, 'crossentropy': 2.5831187984466553}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 126 metrics: {'accuracy': 0.6526, 'crossentropy': 2.671724322128296}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 127 metrics: {'accuracy': 0.6386, 'crossentropy': 2.900815308380127}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 128 metrics: {'accuracy': 0.6572, 'crossentropy': 2.6214982219696044}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 129 metrics: {'accuracy': 0.6624, 'crossentropy': 2.6940071323394776}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 130 metrics: {'accuracy': 0.657, 'crossentropy': 2.6408819049835204}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 131 metrics: {'accuracy': 0.6516, 'crossentropy': 2.711736809921265}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 132 metrics: {'accuracy': 0.6548, 'crossentropy': 2.7338013511657713}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 133 metrics: {'accuracy': 0.66, 'crossentropy': 2.610374885559082}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 134 metrics: {'accuracy': 0.649, 'crossentropy': 2.849789385986328}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 135 metrics: {'accuracy': 0.6596, 'crossentropy': 2.668262892532349}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 136 metrics: {'accuracy': 0.6646, 'crossentropy': 2.5967228511810303}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 137 metrics: {'accuracy': 0.6666, 'crossentropy': 2.5540610416412353}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 138 metrics: {'accuracy': 0.6598, 'crossentropy': 2.6203109561920166}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 139 metrics: {'accuracy': 0.657, 'crossentropy': 2.678562328338623}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 140 metrics: {'accuracy': 0.6622, 'crossentropy': 2.6265086269378664}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 141 metrics: {'accuracy': 0.643, 'crossentropy': 2.8907856174468995}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 142 metrics: {'accuracy': 0.6684, 'crossentropy': 2.6456907455444334}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 143 metrics: {'accuracy': 0.6616, 'crossentropy': 2.6921839332580566}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 144 metrics: {'accuracy': 0.656, 'crossentropy': 2.8150816570281982}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 145 metrics: {'accuracy': 0.6518, 'crossentropy': 2.890988484573364}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 146 metrics: {'accuracy': 0.6392, 'crossentropy': 2.862138520812988}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 147 metrics: {'accuracy': 0.6504, 'crossentropy': 2.8185749015808104}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 148 metrics: {'accuracy': 0.6536, 'crossentropy': 2.825258309173584}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 149 metrics: {'accuracy': 0.6548, 'crossentropy': 2.814702058029175}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 150 metrics: {'accuracy': 0.6594, 'crossentropy': 2.7494749687194826}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 151 metrics: {'accuracy': 0.6616, 'crossentropy': 2.699591756820679}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 152 metrics: {'accuracy': 0.6636, 'crossentropy': 2.5651773036956786}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 153 metrics: {'accuracy': 0.6646, 'crossentropy': 2.5723829193115235}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 154 metrics: {'accuracy': 0.654, 'crossentropy': 2.683935082244873}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 155 metrics: {'accuracy': 0.6578, 'crossentropy': 2.5824686824798584}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 156 metrics: {'accuracy': 0.6634, 'crossentropy': 2.627465510177612}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 157 metrics: {'accuracy': 0.658, 'crossentropy': 2.721166914367676}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 158 metrics: {'accuracy': 0.6678, 'crossentropy': 2.5950584911346435}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 159 metrics: {'accuracy': 0.6654, 'crossentropy': 2.5482390319824217}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 160 metrics: {'accuracy': 0.6728, 'crossentropy': 2.5297875328063966}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 161 metrics: {'accuracy': 0.6642, 'crossentropy': 2.549560933303833}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 162 metrics: {'accuracy': 0.6724, 'crossentropy': 2.514709270095825}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 163 metrics: {'accuracy': 0.6662, 'crossentropy': 2.6739890377044677}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 164 metrics: {'accuracy': 0.6712, 'crossentropy': 2.5637472816467284}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 165 metrics: {'accuracy': 0.6732, 'crossentropy': 2.5383569297790527}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 166 metrics: {'accuracy': 0.6726, 'crossentropy': 2.520796799468994}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 167 metrics: {'accuracy': 0.6716, 'crossentropy': 2.5000243618011475}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 168 metrics: {'accuracy': 0.6716, 'crossentropy': 2.547315874862671}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 169 metrics: {'accuracy': 0.6702, 'crossentropy': 2.5479700859069823}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 170 metrics: {'accuracy': 0.6722, 'crossentropy': 2.5254847366333006}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 171 metrics: {'accuracy': 0.674, 'crossentropy': 2.5466954513549807}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 172 metrics: {'accuracy': 0.675, 'crossentropy': 2.4717196552276612}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 173 metrics: {'accuracy': 0.6724, 'crossentropy': 2.517987104034424}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 174 metrics: {'accuracy': 0.6706, 'crossentropy': 2.542851198577881}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 175 metrics: {'accuracy': 0.6744, 'crossentropy': 2.4931444522857666}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 176 metrics: {'accuracy': 0.6752, 'crossentropy': 2.511356197357178}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 177 metrics: {'accuracy': 0.6766, 'crossentropy': 2.5000491394042967}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 178 metrics: {'accuracy': 0.674, 'crossentropy': 2.4963913146972656}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 179 metrics: {'accuracy': 0.6722, 'crossentropy': 2.515770890045166}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 180 metrics: {'accuracy': 0.6734, 'crossentropy': 2.4821668014526366}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 181 metrics: {'accuracy': 0.6774, 'crossentropy': 2.4697856773376463}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 182 metrics: {'accuracy': 0.674, 'crossentropy': 2.488811835861206}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 183 metrics: {'accuracy': 0.6744, 'crossentropy': 2.5062671604156495}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 184 metrics: {'accuracy': 0.6718, 'crossentropy': 2.523798867416382}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 185 metrics: {'accuracy': 0.6704, 'crossentropy': 2.546375835418701}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 186 metrics: {'accuracy': 0.673, 'crossentropy': 2.517531550216675}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 187 metrics: {'accuracy': 0.6718, 'crossentropy': 2.5210089611053466}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 188 metrics: {'accuracy': 0.6764, 'crossentropy': 2.5385321853637697}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 189 metrics: {'accuracy': 0.6762, 'crossentropy': 2.525834504699707}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 190 metrics: {'accuracy': 0.675, 'crossentropy': 2.5133980121612547}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 191 metrics: {'accuracy': 0.6742, 'crossentropy': 2.4870833194732667}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 192 metrics: {'accuracy': 0.6756, 'crossentropy': 2.508055226135254}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 193 metrics: {'accuracy': 0.6726, 'crossentropy': 2.466618900680542}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 194 metrics: {'accuracy': 0.6738, 'crossentropy': 2.481247635269165}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 195 metrics: {'accuracy': 0.676, 'crossentropy': 2.501637008666992}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 196 metrics: {'accuracy': 0.6736, 'crossentropy': 2.4742876903533935}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 197 metrics: {'accuracy': 0.6728, 'crossentropy': 2.521630255126953}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 198 metrics: {'accuracy': 0.6746, 'crossentropy': 2.484155728149414}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 199 metrics: {'accuracy': 0.6744, 'crossentropy': 2.487708026123047}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 200 metrics: {'accuracy': 0.672, 'crossentropy': 2.510010821533203}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 201 metrics: {'accuracy': 0.6714, 'crossentropy': 2.501680049133301}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 202 metrics: {'accuracy': 0.6742, 'crossentropy': 2.494542570877075}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 203 metrics: {'accuracy': 0.6742, 'crossentropy': 2.5026391651153563}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 204 metrics: {'accuracy': 0.6714, 'crossentropy': 2.479823846435547}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 205 metrics: {'accuracy': 0.6728, 'crossentropy': 2.500494379043579}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 206 metrics: {'accuracy': 0.6742, 'crossentropy': 2.465902960586548}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 207 metrics: {'accuracy': 0.6748, 'crossentropy': 2.507644288635254}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 208 metrics: {'accuracy': 0.6762, 'crossentropy': 2.4923356647491457}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 209 metrics: {'accuracy': 0.6744, 'crossentropy': 2.4851944339752197}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 210 metrics: {'accuracy': 0.676, 'crossentropy': 2.471399641418457}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 211 metrics: {'accuracy': 0.6742, 'crossentropy': 2.48411247215271}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 212 metrics: {'accuracy': 0.6736, 'crossentropy': 2.4647130630493166}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 213 metrics: {'accuracy': 0.6776, 'crossentropy': 2.4999272789001465}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 214 metrics: {'accuracy': 0.6784, 'crossentropy': 2.4666568771362303}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 215 metrics: {'accuracy': 0.6776, 'crossentropy': 2.4399658046722412}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 216 metrics: {'accuracy': 0.6736, 'crossentropy': 2.459940484237671}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 217 metrics: {'accuracy': 0.6764, 'crossentropy': 2.455937529754639}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 218 metrics: {'accuracy': 0.678, 'crossentropy': 2.4509685855865477}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 219 metrics: {'accuracy': 0.675, 'crossentropy': 2.437345257949829}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 220 metrics: {'accuracy': 0.675, 'crossentropy': 2.4548923709869386}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 221 metrics: {'accuracy': 0.6784, 'crossentropy': 2.4382892360687256}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 222 metrics: {'accuracy': 0.676, 'crossentropy': 2.459956135559082}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 223 metrics: {'accuracy': 0.6764, 'crossentropy': 2.4580553783416748}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 224 metrics: {'accuracy': 0.674, 'crossentropy': 2.4496274616241456}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 225 metrics: {'accuracy': 0.6776, 'crossentropy': 2.457004451751709}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 226 metrics: {'accuracy': 0.678, 'crossentropy': 2.4328000297546386}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 227 metrics: {'accuracy': 0.6754, 'crossentropy': 2.4555637378692627}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 228 metrics: {'accuracy': 0.6758, 'crossentropy': 2.4445664875030517}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 229 metrics: {'accuracy': 0.6766, 'crossentropy': 2.449093216705322}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 230 metrics: {'accuracy': 0.6736, 'crossentropy': 2.425094723510742}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 231 metrics: {'accuracy': 0.675, 'crossentropy': 2.4614727993011476}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 232 metrics: {'accuracy': 0.677, 'crossentropy': 2.4432150547027587}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 233 metrics: {'accuracy': 0.6774, 'crossentropy': 2.475752858734131}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 234 metrics: {'accuracy': 0.6748, 'crossentropy': 2.4554464023590086}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 235 metrics: {'accuracy': 0.6776, 'crossentropy': 2.4431961097717285}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 236 metrics: {'accuracy': 0.6768, 'crossentropy': 2.472152670288086}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 237 metrics: {'accuracy': 0.6778, 'crossentropy': 2.4386870681762693}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 238 metrics: {'accuracy': 0.6738, 'crossentropy': 2.4197988330841063}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 239 metrics: {'accuracy': 0.678, 'crossentropy': 2.4275214179992677}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 240 metrics: {'accuracy': 0.6758, 'crossentropy': 2.432341135787964}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 241 metrics: {'accuracy': 0.6756, 'crossentropy': 2.4078450607299806}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 242 metrics: {'accuracy': 0.6766, 'crossentropy': 2.4142181816101074}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 243 metrics: {'accuracy': 0.6738, 'crossentropy': 2.4447541358947755}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 244 metrics: {'accuracy': 0.677, 'crossentropy': 2.4430173404693605}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 245 metrics: {'accuracy': 0.6762, 'crossentropy': 2.4064275592803956}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 246 metrics: {'accuracy': 0.6746, 'crossentropy': 2.441832574462891}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 247 metrics: {'accuracy': 0.6754, 'crossentropy': 2.4583245403289795}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 248 metrics: {'accuracy': 0.6762, 'crossentropy': 2.4131958583831787}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 249 metrics: {'accuracy': 0.6782, 'crossentropy': 2.4499823318481444}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 250 metrics: {'accuracy': 0.6756, 'crossentropy': 2.4543353870391846}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 251 metrics: {'accuracy': 0.6736, 'crossentropy': 2.4446485149383546}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 252 metrics: {'accuracy': 0.6738, 'crossentropy': 2.4498222522735595}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 253 metrics: {'accuracy': 0.674, 'crossentropy': 2.4392303424835204}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 254 metrics: {'accuracy': 0.6742, 'crossentropy': 2.4353042053222658}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 255 metrics: {'accuracy': 0.6784, 'crossentropy': 2.4838941242218016}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 256 metrics: {'accuracy': 0.6778, 'crossentropy': 2.4182816226959227}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 257 metrics: {'accuracy': 0.6764, 'crossentropy': 2.4243657051086425}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 258 metrics: {'accuracy': 0.6766, 'crossentropy': 2.4650497291564943}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 259 metrics: {'accuracy': 0.6766, 'crossentropy': 2.455877131652832}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 260 metrics: {'accuracy': 0.677, 'crossentropy': 2.4400979614257814}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 261 metrics: {'accuracy': 0.674, 'crossentropy': 2.414813304519653}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 262 metrics: {'accuracy': 0.6764, 'crossentropy': 2.4436942234039307}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 263 metrics: {'accuracy': 0.6728, 'crossentropy': 2.4271271675109864}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 264 metrics: {'accuracy': 0.6766, 'crossentropy': 2.420365217971802}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 265 metrics: {'accuracy': 0.6768, 'crossentropy': 2.4282263999938967}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 266 metrics: {'accuracy': 0.6748, 'crossentropy': 2.419319035720825}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 267 metrics: {'accuracy': 0.6764, 'crossentropy': 2.44576756439209}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 268 metrics: {'accuracy': 0.6794, 'crossentropy': 2.4275263942718506}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 269 metrics: {'accuracy': 0.6752, 'crossentropy': 2.4333084587097167}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 270 metrics: {'accuracy': 0.675, 'crossentropy': 2.4635192783355713}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 271 metrics: {'accuracy': 0.6764, 'crossentropy': 2.4337949756622312}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 272 metrics: {'accuracy': 0.6742, 'crossentropy': 2.421456132888794}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 273 metrics: {'accuracy': 0.6754, 'crossentropy': 2.4948803550720213}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 274 metrics: {'accuracy': 0.6762, 'crossentropy': 2.4148812217712403}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 275 metrics: {'accuracy': 0.6736, 'crossentropy': 2.430330587387085}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 276 metrics: {'accuracy': 0.6752, 'crossentropy': 2.4521533084869387}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 277 metrics: {'accuracy': 0.6762, 'crossentropy': 2.457790599822998}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 278 metrics: {'accuracy': 0.677, 'crossentropy': 2.4241583477020265}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 279 metrics: {'accuracy': 0.6786, 'crossentropy': 2.428473749923706}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 280 metrics: {'accuracy': 0.6766, 'crossentropy': 2.4389997650146484}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 281 metrics: {'accuracy': 0.674, 'crossentropy': 2.4454905895233154}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 282 metrics: {'accuracy': 0.6756, 'crossentropy': 2.403413757324219}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 283 metrics: {'accuracy': 0.6782, 'crossentropy': 2.413132022857666}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 284 metrics: {'accuracy': 0.6788, 'crossentropy': 2.4135424282073976}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 285 metrics: {'accuracy': 0.6786, 'crossentropy': 2.4336018367767336}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 286 metrics: {'accuracy': 0.6738, 'crossentropy': 2.385467792892456}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 287 metrics: {'accuracy': 0.6762, 'crossentropy': 2.4554801387786864}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 288 metrics: {'accuracy': 0.6758, 'crossentropy': 2.4104957710266115}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 289 metrics: {'accuracy': 0.6786, 'crossentropy': 2.4168723720550536}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 290 metrics: {'accuracy': 0.678, 'crossentropy': 2.4242772369384764}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 291 metrics: {'accuracy': 0.6778, 'crossentropy': 2.4174008445739745}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 292 metrics: {'accuracy': 0.6762, 'crossentropy': 2.452844713973999}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 293 metrics: {'accuracy': 0.676, 'crossentropy': 2.44308024520874}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 294 metrics: {'accuracy': 0.678, 'crossentropy': 2.4303935497283935}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 295 metrics: {'accuracy': 0.6762, 'crossentropy': 2.4341884449005127}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 296 metrics: {'accuracy': 0.6794, 'crossentropy': 2.4184077697753907}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 297 metrics: {'accuracy': 0.6752, 'crossentropy': 2.4065731983184815}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 298 metrics: {'accuracy': 0.676, 'crossentropy': 2.4273660774230956}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 299 metrics: {'accuracy': 0.6746, 'crossentropy': 2.4285712856292725}


[1/39]   3%|2          [00:00<?]

[1/10]  10%|#          [00:00<?]

Epoch 300 metrics: {'accuracy': 0.6726, 'crossentropy': 2.4365912525177}


In [ ]:
# experiment

evaluate(model=trained_model, num_samples=50, loader=test_loader, device="cuda")

get_predictions_labels:   0%|          | 0/500000 [00:00<?, ?it/s]

{'accuracy': 0.6753, 'crossentropy': tensor(1.8744)}

## CIFAR-100

In [ ]:
# experiment 
split_dataset = get_dataset("CIFAR-100", normalize_like_cifar10=False, train_augmentation=True, validation_set_size=5000)

Files already downloaded and verified


In [ ]:
# experiment

from torch.utils import data

kwargs = {"num_workers": 4, "pin_memory": True}

train_loader = data.DataLoader(split_dataset.train * 0.4, batch_size=128, shuffle=True, **kwargs)
validation_loader = data.DataLoader(split_dataset.validation, batch_size=128, shuffle=False, **kwargs)
test_loader = data.DataLoader(split_dataset.test, batch_size=128, shuffle=False, **kwargs)

model_optimizer = Cifar10BayesianResnetFactory().create_model_optimizer()
train_with_schedule(model=model_optimizer.model, optimizer=model_optimizer.optimizer, train_loader=train_loader, validation_loader=validation_loader, patience_schedule=[3,3,3,3], factor_schedule=[0.1], max_epochs=80, device="cuda", training_samples=1, validation_samples=10, training_log={})

  2%|1         | 1/60 [00:00<?, ?it/s]

[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.037, 'crossentropy': 4.40652554473877}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.0492, 'crossentropy': 4.2037655502319335}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.061, 'crossentropy': 4.198613374328613}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.0564, 'crossentropy': 4.067956605148315}
Epoch 4: 0.0564 worse than 0.061, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.0838, 'crossentropy': 4.026535692596435}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.0804, 'crossentropy': 4.04006093826294}
Epoch 6: 0.0804 worse than 0.0838, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.0916, 'crossentropy': 3.950498880004883}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1032, 'crossentropy': 3.9708983085632323}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1142, 'crossentropy': 3.8166026466369627}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.117, 'crossentropy': 3.8180666912078856}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1002, 'crossentropy': 3.947795548248291}
Epoch 11: 0.1002 worse than 0.117, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1012, 'crossentropy': 3.8586297302246093}
Epoch 12: 0.1012 worse than 0.117, patience: 2/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1334, 'crossentropy': 3.7211234298706053}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1526, 'crossentropy': 3.6456055068969726}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1506, 'crossentropy': 3.639182250213623}
Epoch 15: 0.1506 worse than 0.1526, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1556, 'crossentropy': 3.5743414745330813}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1798, 'crossentropy': 3.5142369106292723}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1766, 'crossentropy': 3.4968504013061525}
Epoch 18: 0.1766 worse than 0.1798, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.19, 'crossentropy': 3.415262245178223}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2, 'crossentropy': 3.436680059814453}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2038, 'crossentropy': 3.479621842575073}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.1874, 'crossentropy': 3.492301457977295}
Epoch 22: 0.1874 worse than 0.2038, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2194, 'crossentropy': 3.321240447998047}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2264, 'crossentropy': 3.2894559776306154}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2468, 'crossentropy': 3.2592536624908446}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.255, 'crossentropy': 3.1534479541778566}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2574, 'crossentropy': 3.194382339859009}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2588, 'crossentropy': 3.2088769870758056}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2538, 'crossentropy': 3.1996145584106443}
Epoch 29: 0.2538 worse than 0.2588, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2868, 'crossentropy': 3.048496583557129}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.285, 'crossentropy': 3.0462064266204836}
Epoch 31: 0.285 worse than 0.2868, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.2916, 'crossentropy': 3.0441914291381837}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3042, 'crossentropy': 2.9938636936187746}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3142, 'crossentropy': 2.9616074798583982}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3128, 'crossentropy': 3.0372639751434325}
Epoch 35: 0.3128 worse than 0.3142, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3266, 'crossentropy': 2.9172872680664064}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.332, 'crossentropy': 2.8956572322845457}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3346, 'crossentropy': 2.8784393520355223}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3478, 'crossentropy': 2.834599676513672}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3372, 'crossentropy': 2.8797668670654297}
Epoch 40: 0.3372 worse than 0.3478, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3616, 'crossentropy': 2.7556054058074952}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3524, 'crossentropy': 2.8509595169067383}
Epoch 42: 0.3524 worse than 0.3616, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3544, 'crossentropy': 2.8260359642028807}
Epoch 43: 0.3544 worse than 0.3616, patience: 2/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3708, 'crossentropy': 2.761400556564331}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3746, 'crossentropy': 2.743904900741577}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3752, 'crossentropy': 2.752844585418701}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.391, 'crossentropy': 2.7870617553710937}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3912, 'crossentropy': 2.6811590377807617}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.392, 'crossentropy': 2.7096566692352293}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3922, 'crossentropy': 2.6482392658233644}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4076, 'crossentropy': 2.69913618888855}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3926, 'crossentropy': 2.7104971210479736}
Epoch 52: 0.3926 worse than 0.4076, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4212, 'crossentropy': 2.7271564582824706}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.3974, 'crossentropy': 2.7731422164916992}
Epoch 54: 0.3974 worse than 0.4212, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4226, 'crossentropy': 2.7127608409881594}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4286, 'crossentropy': 2.686399506378174}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4234, 'crossentropy': 2.731360105895996}
Epoch 57: 0.4234 worse than 0.4286, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4368, 'crossentropy': 2.6142911724090574}


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4238, 'crossentropy': 2.699748579788208}
Epoch 59: 0.4238 worse than 0.4368, patience: 1/3!


[1/141]   1%|           [00:00<?]

[1/40]   2%|2          [00:00<?]

Epoch metrics: {'accuracy': 0.4228, 'crossentropy': 2.831049083137512}
Epoch 60: 0.4228 worse than 0.4368, patience: 2/3!


AdamW (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.005
    weight_decay: 0.0005
)

In [ ]:
# experiment

evaluate_old(model=model_optimizer.model, num_samples=20, loader=test_loader, device="cuda")

[1/79]   1%|1          [00:00<?]

{'accuracy': 0.5724, 'crossentropy': 3.0206112657546997}

57.24% is better than Random acquisition in VAAL (Variational Adversarial Active Learning, https://arxiv.org/abs/1904.00370) and also better than the reported CoreSet AL results: 50.5%?

---

"Task-Aware Variational Adversarial Active Learning" (https://arxiv.org/abs/2002.04709) reports much better numbers for Random on ResNet, however: 64%.

They state:

> ResNet18 [13] was used for all task learners and stochastic gradient descent (SGD) was used with momentum 0.9 and weight decay 0.005. Learning rate was 0.1 for the first 160 epochs and then 0.01 for the last 40 epochs.

We leave this as a TODO.