# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"compute_conditional_entropy": "01_batchbald.ipynb",
         "compute_entropy": "01_batchbald.ipynb",
         "CandidateBatch": "01_batchbald.ipynb",
         "BatchBALDScorer": "01_batchbald.ipynb",
         "get_batchbald_batch": "01_batchbald.ipynb",
         "get_batchbald_batch_plain": "01_batchbald.ipynb",
         "get_bald_scores": "01_batchbald.ipynb",
         "get_bald_batch": "01_batchbald.ipynb",
         "get_batchbaldical_batch": "01_batchbald.ipynb",
         "compute_each_conditional_entropy": "01_batchbald.ipynb",
         "get_thompson_bald_batch": "01_batchbald.ipynb",
         "get_random_bald_batch": "01_batchbald.ipynb",
         "JointEntropy": "02_joint_entropy_computation.ipynb",
         "ExactJointEntropy": "02_joint_entropy_computation.ipynb",
         "batch_multi_choices": "02_joint_entropy_computation.ipynb",
         "gather_expand": "02_joint_entropy_computation.ipynb",
         "gather_expand.DEBUG_CHECKS": "02_joint_entropy_computation.ipynb",
         "SampledJointEntropy": "02_joint_entropy_computation.ipynb",
         "DynamicJointEntropy": "02_joint_entropy_computation.ipynb",
         "BayesianModule": "03_consistent_mc_dropout.ipynb",
         "ConsistentMCDropout": "03_consistent_mc_dropout.ipynb",
         "ConsistentMCDropout2d": "03_consistent_mc_dropout.ipynb",
         "SamplerModel": "03_consistent_mc_dropout.ipynb",
         "multi_sample_loss": "03_consistent_mc_dropout.ipynb",
         "geometric_mean_loss": "03_consistent_mc_dropout.ipynb",
         "GeometricMeanPrediction": "03_consistent_mc_dropout.ipynb",
         "ActiveLearningData": "04_active_learning.ipynb",
         "get_balanced_sample_indices": "04_active_learning.ipynb",
         "get_subset_base_indices": "04_active_learning.ipynb",
         "get_base_indices": "04_active_learning.ipynb",
         "RandomFixedLengthSampler": "04_active_learning.ipynb",
         "FastMNIST": "05a_fast_mnist.ipynb",
         "TransformedDataset": "05b_repeated_mnist.ipynb",
         "create_repeated_MNIST_dataset": "05b_repeated_mnist.ipynb",
         "create_MNIST_dataset": "05b_repeated_mnist.ipynb",
         "get_targets": "05b_repeated_mnist.ipynb",
         "RestoringEarlyStopping": "05c_restoring_early_stopping.ipynb",
         "train": "07_black_box_training.ipynb",
         "evaluate": "07_black_box_training.ipynb",
         "create_metrics": "07_black_box_training.ipynb",
         "LOG_INTERVAL": "07_black_box_training.ipynb",
         "get_predictions": "07_black_box_training.ipynb",
         "AcquisitionFunction": "09_experiment.ipynb",
         "PredictionDataset": "09_experiment.ipynb",
         "mnist_initial_samples": "09_experiment.ipynb",
         "Experiment": "09_experiment.ipynb",
         "BayesianMNISTCNN": "A1_some_models.ipynb",
         "BayesianMNISTCNN_EBM": "A1_some_models.ipynb"}

modules = ["batchbald.py",
           "joint_entropy.py",
           "consistent_mc_dropout.py",
           "active_learning.py",
           "fast_mnist.py",
           "repeated_mnist.py",
           "restoring_early_stopping.py",
           "black_box_model_training.py",
           "experiment.py",
           "example_models.py"]

doc_url = "https://blackhc.github.io/batchbald_redux/"

git_url = "https://github.com/blackhc/batchbald_redux/tree/master/"

def custom_doc_links(name): return None
